import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function encodeBase64(value: string) {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (let index = 0; index < bytes.length; index += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000));
  }
  return btoa(binary);
}

function required(name: string) {
  const value = Deno.env.get(name)?.trim();
  if (!value) throw new Error(`Missing Supabase secret: ${name}`);
  return value;
}

Deno.serve(async request => {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (request.method !== "POST") return json({ error: "Method not allowed" }, 405);

  try {
    const authorization = request.headers.get("Authorization");
    if (!authorization) return json({ error: "Authentication required" }, 401);

    const supabase = createClient(
      required("SUPABASE_URL"),
      required("SUPABASE_ANON_KEY"),
      { global: { headers: { Authorization: authorization } } },
    );
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) return json({ error: "Invalid session" }, 401);

    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("plan")
      .eq("id", user.id)
      .maybeSingle();
    if (profileError) throw profileError;
    if (profile?.plan !== "admin") return json({ error: "Only administrators can publish the catalog" }, 403);

    const payload = await request.json();
    if (!Array.isArray(payload.library) || !Array.isArray(payload.series) || !Array.isArray(payload.collections)) {
      return json({ error: "Invalid catalog payload" }, 400);
    }

    const repository = required("GITHUB_REPOSITORY");
    const branch = Deno.env.get("GITHUB_BRANCH")?.trim() || "main";
    const path = Deno.env.get("GITHUB_CATALOG_PATH")?.trim() || "js/data/dc-comics/recentes.js";
    const token = required("GITHUB_TOKEN");
    const source = `/* Generated by the Banca Digital admin panel. */\nwindow.CATALOG_VERSION = ${JSON.stringify(new Date().toISOString())};\nwindow.DEFAULT_SERIES = ${JSON.stringify(payload.series, null, 2)};\nwindow.DEFAULT_LIBRARY = ${JSON.stringify(payload.library, null, 2)};\nwindow.DEFAULT_COLLECTIONS = ${JSON.stringify(payload.collections, null, 2)};\n`;
    const encodedPath = path.split("/").map(encodeURIComponent).join("/");
    const apiUrl = `https://api.github.com/repos/${repository}/contents/${encodedPath}`;
    const headers = {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
    };

    const current = await fetch(`${apiUrl}?ref=${encodeURIComponent(branch)}`, { headers });
    if (!current.ok && current.status !== 404) {
      throw new Error(`GitHub read failed with HTTP ${current.status}`);
    }
    const currentFile = current.status === 404 ? null : await current.json();
    const update = await fetch(apiUrl, {
      method: "PUT",
      headers: { ...headers, "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `Update catalog via Banca Digital (${new Date().toISOString()})`,
        content: encodeBase64(source),
        branch,
        ...(currentFile?.sha ? { sha: currentFile.sha } : {}),
      }),
    });

    if (!update.ok) {
      const detail = await update.text();
      throw new Error(`GitHub write failed with HTTP ${update.status}: ${detail.slice(0, 300)}`);
    }

    const result = await update.json();
    return json({ ok: true, commit: result.commit?.sha || null, path, branch });
  } catch (error) {
    console.error("github-catalog", error);
    return json({ error: error instanceof Error ? error.message : "Catalog publish failed" }, 500);
  }
});
