import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const sourceFields = ["coverUrl", "cover", "featuredCoverUrl", "fileUrl", "telegramUrl", "telegramFileId", "telegramFileName", "telegramFileSize", "backupUrls", "customLinks", "format"];
const indexOmitFields = new Set([
  "fileUrl", "telegramUrl", "telegramFileId", "telegramFileName", "telegramFileSize",
  "backupUrls", "customLinks", "blogUrl", "officialUrl", "sourceUrl", "description",
  "collectionIds", "clicks", "downloadCount",
]);
const inheritedSeriesFields = [
  "seriesTitle", "author", "publisher", "imprint", "year", "description", "coverUrl",
  "telegramUrl", "tags", "type", "publication", "status", "editions", "character",
];

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}
function encodeBase64(value: string) {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000));
  return btoa(binary);
}
function required(name: string) {
  const value = Deno.env.get(name)?.trim();
  if (!value) throw new Error(`Missing Supabase secret: ${name}`);
  return value;
}
type Edition = Record<string, unknown> & { id: string };
type Override = { item_id: string; edition: Edition; updated_at: string };

function applyOverride(item: Edition, record: Override): Edition {
  const merged: Edition = { ...item, ...record.edition, catalogEditedAt: record.updated_at };
  for (const field of sourceFields) {
    if (Object.prototype.hasOwnProperty.call(record.edition, field)) merged[field] = record.edition[field];
    else delete merged[field];
  }
  return merged;
}
function reconcile(library: Edition[], records: Override[]): Edition[] {
  const overrides = new Map(records.filter(row => row.edition && String(row.edition.id) === String(row.item_id)).map(row => [String(row.item_id), row]));
  const merged = library.map(item => {
    const record = overrides.get(String(item.id));
    return record ? applyOverride(item, record) : item;
  });
  const known = new Set(merged.map(item => String(item.id)));
  for (const [id, record] of overrides) if (!known.has(id)) merged.push(applyOverride({ ...record.edition }, record));
  return merged.filter(item => item.catalogDeleted !== true);
}
function sameValue(left: unknown, right: unknown) {
  return JSON.stringify(left) === JSON.stringify(right);
}
function lightweightEdition(item: Edition, seriesById: Map<string, Record<string, unknown>>): Edition {
  const compact = Object.fromEntries(Object.entries(item).filter(([key]) => !indexOmitFields.has(key))) as Edition;
  const definition = seriesById.get(String(item.seriesId || ""));
  if (definition) {
    for (const field of inheritedSeriesFields) {
      if (field === "type") continue;
      if (Object.prototype.hasOwnProperty.call(compact, field) && sameValue(compact[field], definition[field])) delete compact[field];
    }
    if (compact.seriesTitle === definition.name || compact.seriesTitle === definition.seriesTitle) delete compact.seriesTitle;
  }
  return compact;
}
function catalogSource(version: string, removedItemIds: string[], series: unknown[], library: Edition[], collections: unknown[]) {
  return `/* Generated by the Banca Digital admin panel. */
window.CATALOG_VERSION = ${JSON.stringify(version)};
window.REMOVED_DEFAULT_ITEM_IDS = ${JSON.stringify(removedItemIds)};
window.DEFAULT_SERIES = ${JSON.stringify(series, null, 2)};
window.DEFAULT_LIBRARY = ${JSON.stringify(library, null, 2)};
window.DEFAULT_COLLECTIONS = ${JSON.stringify(collections, null, 2)};
`;
}
function catalogIndexSource(version: string, removedItemIds: string[], series: Record<string, unknown>[], library: Edition[], collections: unknown[]) {
  const seriesById = new Map(series.map(entry => [String(entry.id || ""), entry]));
  return `/* Generated lightweight catalog index. Full edition sources load on demand. */
window.BANCA_CATALOG_LITE=true;
window.CATALOG_VERSION=${JSON.stringify(version)};
window.REMOVED_DEFAULT_ITEM_IDS=${JSON.stringify(removedItemIds)};
window.DEFAULT_SERIES=${JSON.stringify(series)};
window.DEFAULT_LIBRARY=${JSON.stringify(library.map(item => lightweightEdition(item, seriesById)))};
window.DEFAULT_COLLECTIONS=${JSON.stringify(collections)};
`;
}

async function writeGitHubFile(repository: string, branch: string, path: string, token: string, content: string, message: string) {
  const encodedPath = path.split("/").map(encodeURIComponent).join("/");
  const apiUrl = `https://api.github.com/repos/${repository}/contents/${encodedPath}`;
  const headers = { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "X-GitHub-Api-Version": "2022-11-28" };
  for (let attempt = 0; attempt < 3; attempt++) {
    const current = await fetch(`${apiUrl}?ref=${encodeURIComponent(branch)}`, { headers, cache: "no-store" });
    if (!current.ok && current.status !== 404) throw new Error(`GitHub read failed for ${path} with HTTP ${current.status}`);
    const currentFile = current.status === 404 ? null : await current.json();
    const update = await fetch(apiUrl, {
      method: "PUT",
      headers: { ...headers, "Content-Type": "application/json" },
      body: JSON.stringify({
        message,
        content: encodeBase64(content),
        branch,
        ...(currentFile?.sha ? { sha: currentFile.sha } : {}),
      }),
    });
    if (update.ok) return await update.json();
    if ((update.status === 409 || update.status === 422) && attempt < 2) continue;
    const detail = await update.text();
    throw new Error(`GitHub write failed for ${path} with HTTP ${update.status}: ${detail.slice(0, 300)}`);
  }
  throw new Error(`GitHub publication could not be confirmed for ${path}`);
}

Deno.serve(async request => {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (request.method !== "POST") return json({ error: "Method not allowed" }, 405);
  try {
    const authorization = request.headers.get("Authorization");
    if (!authorization) return json({ error: "Authentication required" }, 401);
    const supabase = createClient(required("SUPABASE_URL"), required("SUPABASE_ANON_KEY"), { global: { headers: { Authorization: authorization } } });
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) return json({ error: "Invalid session" }, 401);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("plan").eq("id", user.id).maybeSingle();
    if (profileError) throw profileError;
    if (profile?.plan !== "admin") return json({ error: "Only administrators can publish the catalog" }, 403);

    const payload = await request.json();
    if (!Array.isArray(payload.library) || !Array.isArray(payload.series) || !Array.isArray(payload.collections)) return json({ error: "Invalid catalog payload" }, 400);
    if (payload.library.some((item: Edition) => !item || typeof item.id !== "string" || !item.id)) return json({ error: "Invalid edition identifier" }, 400);

    const { data: records, error: recordsError } = await supabase.from("catalog_edition_overrides").select("item_id,edition,updated_at").order("item_id").limit(10000);
    if (recordsError) throw recordsError;
    const library = reconcile(payload.library, (records || []) as Override[]);
    const removedItemIds = (records || []).filter((row: Override) => row.edition?.catalogDeleted === true).map((row: Override) => row.item_id);
    const repository = required("GITHUB_REPOSITORY");
    const branch = Deno.env.get("GITHUB_BRANCH")?.trim() || "main";
    const fullPath = Deno.env.get("GITHUB_CATALOG_PATH")?.trim() || "js/data/dc-comics/recentes.js";
    const indexPath = Deno.env.get("GITHUB_CATALOG_INDEX_PATH")?.trim() || fullPath.replace(/[^/]+$/, "catalog-index.js");
    const token = required("GITHUB_TOKEN");
    const version = new Date().toISOString();
    const message = `Update catalog via Banca Digital (${version})`;

    const fullResult = await writeGitHubFile(repository, branch, fullPath, token, catalogSource(version, removedItemIds, payload.series, library, payload.collections), message);
    const indexResult = await writeGitHubFile(repository, branch, indexPath, token, catalogIndexSource(version, removedItemIds, payload.series, library, payload.collections), message);

    return json({
      ok: true,
      commit: indexResult.commit?.sha || fullResult.commit?.sha || null,
      fullPath,
      indexPath,
      branch,
      shared: true,
      initialEditionFields: Object.keys(lightweightEdition(library[0] || ({ id: "" } as Edition), new Map((payload.series as Record<string, unknown>[]).map((entry: Record<string, unknown>) => [String(entry.id || ""), entry])))).length,
    });
  } catch (error) {
    console.error("github-catalog", error);
    return json({ error: error instanceof Error ? error.message : "Catalog publish failed" }, 500);
  }
});
