-- Registro público temporário da atividade da comunidade.
-- Diferente de notifications, não possui destinatário e não gera badge.
create table if not exists public.community_activity (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null check (event_type in ('comment', 'completed', 'like')),
  title text not null check (char_length(title) between 1 and 160),
  body text not null check (char_length(body) between 1 and 1000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create index if not exists community_activity_created_idx on public.community_activity(created_at desc);
create index if not exists community_activity_expires_idx on public.community_activity(expires_at);

create or replace function public.purge_expired_community_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  delete from public.community_activity where expires_at <= now();
  return new;
end;
$$;

drop trigger if exists purge_expired_community_activity_trigger on public.community_activity;
create trigger purge_expired_community_activity_trigger
before insert on public.community_activity
for each statement execute procedure public.purge_expired_community_activity();
revoke execute on function public.purge_expired_community_activity() from anon, authenticated;

create or replace function public.record_community_activity(
  p_actor_id uuid,
  p_event_type text,
  p_title text,
  p_body text,
  p_metadata jsonb default '{}'::jsonb
)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if p_actor_id is null then return; end if;
  insert into public.community_activity(actor_id, event_type, title, body, metadata)
  values (p_actor_id, p_event_type, left(p_title, 160), left(p_body, 1000), coalesce(p_metadata, '{}'::jsonb));
end;
$$;

revoke execute on function public.record_community_activity(uuid, text, text, text, jsonb) from anon, authenticated;

create or replace function public.record_comic_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'comment', 'Novo comentário', NEW.body,
    jsonb_build_object('source', 'comic', 'item_id', NEW.item_id, 'comment_id', NEW.id));
  return NEW;
end;
$$;

drop trigger if exists record_comic_comment_activity_trigger on public.comments;
create trigger record_comic_comment_activity_trigger after insert on public.comments for each row execute procedure public.record_comic_comment_activity();
revoke execute on function public.record_comic_comment_activity() from anon, authenticated;

create or replace function public.record_blog_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'comment', 'Novo comentário em blog', NEW.body,
    jsonb_build_object('source', 'blog', 'blog_id', NEW.blog_id, 'comment_id', NEW.id));
  return NEW;
end;
$$;

drop trigger if exists record_blog_comment_activity_trigger on public.blog_comments;
create trigger record_blog_comment_activity_trigger after insert on public.blog_comments for each row execute procedure public.record_blog_comment_activity();
revoke execute on function public.record_blog_comment_activity() from anon, authenticated;

create or replace function public.record_wall_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'comment', 'Novo comentário em mural', NEW.body,
    jsonb_build_object('source', 'profile_wall', 'profile_id', NEW.profile_id, 'comment_id', NEW.id));
  return NEW;
end;
$$;

drop trigger if exists record_wall_comment_activity_trigger on public.profile_wall_comments;
create trigger record_wall_comment_activity_trigger after insert on public.profile_wall_comments for each row execute procedure public.record_wall_comment_activity();
revoke execute on function public.record_wall_comment_activity() from anon, authenticated;

create or replace function public.record_collection_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'comment', 'Novo comentário em coleção', NEW.body,
    jsonb_build_object('source', 'collection', 'collection_id', NEW.collection_id, 'comment_id', NEW.id));
  return NEW;
end;
$$;

drop trigger if exists record_collection_comment_activity_trigger on public.shelf_collection_comments;
create trigger record_collection_comment_activity_trigger after insert on public.shelf_collection_comments for each row execute procedure public.record_collection_comment_activity();
revoke execute on function public.record_collection_comment_activity() from anon, authenticated;

create or replace function public.record_top10_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'comment', 'Novo comentário em lista', NEW.body,
    jsonb_build_object('source', 'top10', 'list_id', NEW.list_id, 'comment_id', NEW.id));
  return NEW;
end;
$$;

drop trigger if exists record_top10_comment_activity_trigger on public.profile_top10_list_comments;
create trigger record_top10_comment_activity_trigger after insert on public.profile_top10_list_comments for each row execute procedure public.record_top10_comment_activity();
revoke execute on function public.record_top10_comment_activity() from anon, authenticated;

create or replace function public.record_comic_like_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.record_community_activity(NEW.user_id, 'like', 'História curtida', 'Alguém curtiu uma história.',
    jsonb_build_object('source', 'comic', 'item_id', NEW.item_id));
  return NEW;
end;
$$;

drop trigger if exists record_comic_like_activity_trigger on public.comic_likes;
create trigger record_comic_like_activity_trigger after insert on public.comic_likes for each row execute procedure public.record_comic_like_activity();
revoke execute on function public.record_comic_like_activity() from anon, authenticated;

create or replace function public.record_completion_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if NEW.completed and (TG_OP = 'INSERT' or not coalesce(OLD.completed, false)) then
    perform public.record_community_activity(NEW.user_id, 'completed', 'História concluída', 'Alguém concluiu uma história.',
      jsonb_build_object('source', 'comic', 'item_id', NEW.item_id));
  end if;
  return NEW;
end;
$$;

drop trigger if exists record_completion_activity_trigger on public.reading_progress;
create trigger record_completion_activity_trigger after insert or update of completed on public.reading_progress for each row execute procedure public.record_completion_activity();
revoke execute on function public.record_completion_activity() from anon, authenticated;

alter table public.community_activity enable row level security;
grant select on public.community_activity to authenticated;
drop policy if exists "community activity is public" on public.community_activity;
create policy "community activity is public" on public.community_activity for select using (
  expires_at > now() and auth.uid() is not null and (actor_id is null or not public.is_blocked_between(actor_id))
);
