-- Conquistas reais das facções, com progresso por temporada.
create table if not exists public.faction_achievements (
  id bigint generated by default as identity primary key,
  achievement_key text not null unique,
  name text not null,
  description text not null,
  icon text not null default '★',
  metric text not null check (metric in ('xp', 'members', 'read', 'comment', 'like', 'chat', 'follow', 'mandatory_readers', 'sticker', 'sticker_donate', 'sticker_trade')),
  threshold integer not null check (threshold > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.faction_achievements drop constraint if exists faction_achievements_metric_check;
alter table public.faction_achievements add constraint faction_achievements_metric_check check (metric in ('xp', 'members', 'read', 'comment', 'like', 'chat', 'follow', 'mandatory_readers', 'sticker', 'sticker_donate', 'sticker_trade'));
alter table public.faction_achievements add column if not exists created_at timestamptz not null default now();
create table if not exists public.faction_achievement_awards (
  faction_id text not null references public.factions(id) on delete cascade,
  season_id bigint not null references public.faction_seasons(id) on delete cascade,
  achievement_id bigint not null references public.faction_achievements(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (faction_id, season_id, achievement_id)
);
insert into public.faction_achievements(achievement_key, name, description, icon, metric, threshold, sort_order) values
  ('faction_first_steps', 'Primeiros passos', 'A facção soma 1.000 XP nesta temporada. Leituras, comentários, curtidas e mensagens no chat dos membros contribuem.', '✦', 'xp', 1000, 1),
  ('faction_readers', 'Clube da leitura', 'Membros da facção precisam ler 100 edições nesta temporada. A leitura é registrada automaticamente ao chegar ao final da edição.', '📖', 'read', 100, 2),
  ('faction_voice', 'Voz ativa', 'Membros da facção precisam publicar 100 comentários nesta temporada.', '💬', 'comment', 100, 3),
  ('faction_chat', 'Ponto de encontro', 'Membros da facção precisam enviar 100 mensagens nos chats nesta temporada.', '⚡', 'chat', 100, 4),
  ('faction_unity', 'União', 'A facção precisa ter 100 membros atualmente.', '♛', 'members', 100, 5),
  ('faction_loved', 'Querida da banca', 'Membros da facção precisam dar 250 curtidas em quadrinhos nesta temporada.', '♥', 'like', 250, 6),
  ('faction_network', 'Rede formada', 'Membros da facção precisam seguir 100 perfis nesta temporada.', '✧', 'follow', 100, 7),
  ('faction_legend', 'Lenda da temporada', 'A facção soma 10.000 XP nesta temporada. As atividades dos membros contribuem.', '🏆', 'xp', 10000, 8)
on conflict (achievement_key) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, metric = excluded.metric, threshold = excluded.threshold, sort_order = excluded.sort_order;

create or replace function public.get_faction_achievements(p_faction_id text)
returns table(achievement_id bigint, achievement_key text, name text, description text, icon text, metric text, threshold integer, progress integer, unlocked boolean, unlocked_at timestamptz)
language plpgsql security definer set search_path = public
as $$
#variable_conflict use_column
declare v_season public.faction_seasons%rowtype;
begin
  if not exists (select 1 from public.factions where id = p_faction_id) then return; end if;
  v_season := public.current_faction_season();
  with metrics as (
    select a.id, case a.metric
      when 'xp' then coalesce((select sum(xp) from public.faction_xp_events where season_id = v_season.id and faction_id = p_faction_id), 0)
      when 'members' then (select count(*) from public.faction_memberships where faction_id = p_faction_id)
      else (select count(*) from public.faction_xp_events where season_id = v_season.id and faction_id = p_faction_id and event_type = a.metric)
    end::integer as progress
    from public.faction_achievements a
  )
  insert into public.faction_achievement_awards(faction_id, season_id, achievement_id)
  select p_faction_id, v_season.id, metrics.id from metrics join public.faction_achievements a on a.id = metrics.id where metrics.progress >= a.threshold
  on conflict (faction_id, season_id, achievement_id) do nothing;
  return query
  with metrics as (
    select a.id, case a.metric
      when 'xp' then coalesce((select sum(xp) from public.faction_xp_events where season_id = v_season.id and faction_id = p_faction_id), 0)
      when 'members' then (select count(*) from public.faction_memberships where faction_id = p_faction_id)
      else (select count(*) from public.faction_xp_events where season_id = v_season.id and faction_id = p_faction_id and event_type = a.metric)
    end::integer as progress
    from public.faction_achievements a
  )
  select a.id, a.achievement_key, a.name, a.description, a.icon, a.metric, a.threshold, least(metrics.progress, a.threshold), metrics.progress >= a.threshold, case when metrics.progress >= a.threshold then awards.unlocked_at else null end
  from metrics join public.faction_achievements a on a.id = metrics.id
  left join public.faction_achievement_awards awards on awards.faction_id = p_faction_id and awards.season_id = v_season.id and awards.achievement_id = a.id
  order by a.created_at desc, a.sort_order, a.id;
end;
$$;
grant execute on function public.get_faction_achievements(text) to anon, authenticated;
alter table public.faction_achievements enable row level security;
alter table public.faction_achievement_awards enable row level security;
drop policy if exists "faction achievements are public" on public.faction_achievements;
drop policy if exists "faction achievement awards are public" on public.faction_achievement_awards;
create policy "faction achievements are public" on public.faction_achievements for select using (true);
create policy "faction achievement awards are public" on public.faction_achievement_awards for select using (true);

-- Conquistas de figurinhas: os eventos são registrados pela migration de triggers.
insert into public.faction_achievements (achievement_key, name, description, icon, metric, threshold, sort_order) values
  ('faction_sticker_collectors', 'Álbum compartilhado', 'A facção precisa conquistar 100 figurinhas na temporada. Vale obter por leitura, sorte, doação ou troca.', '🎴', 'sticker', 100, 10),
  ('faction_sticker_donors', 'Mãos generosas', 'Membros da facção precisam realizar 25 doações de figurinhas na temporada.', '🎁', 'sticker_donate', 25, 11),
  ('faction_sticker_traders', 'Mercadores da banca', 'Membros da facção precisam concluir 25 trocas de figurinhas na temporada.', '🔄', 'sticker_trade', 25, 12)
on conflict (achievement_key) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, metric = excluded.metric, threshold = excluded.threshold, sort_order = excluded.sort_order;
notify pgrst, 'reload schema';
