-- Álbum de figurinhas por personagem.
-- Execute depois do schema principal.

alter table public.profiles
  add column if not exists allow_sticker_requests boolean not null default true;

create table if not exists public.sticker_awards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id text not null,
  character_name text not null,
  publisher_name text not null,
  edition_fingerprint text not null,
  cover_item_id text not null,
  cover_url text not null check (cover_url ~ '^https://|^data:image/'),
  rarity text not null default 'standard' check (rarity in ('standard', 'torn', 'creased', 'silver', 'gold')),
  awarded_at timestamptz not null default now(),
  unique (user_id, character_id, edition_fingerprint)
);
alter table public.sticker_awards drop constraint if exists sticker_awards_rarity_check;
alter table public.sticker_awards add constraint sticker_awards_rarity_check check (rarity in ('standard', 'torn', 'creased', 'silver', 'gold'));
create index if not exists sticker_awards_user_idx on public.sticker_awards(user_id, character_name);
create index if not exists sticker_awards_character_idx on public.sticker_awards(character_id, awarded_at desc);
alter table public.sticker_awards add column if not exists album_section text not null default 'pasted';
alter table public.sticker_awards drop constraint if exists sticker_awards_album_section_check;
alter table public.sticker_awards add constraint sticker_awards_album_section_check check (album_section in ('pasted', 'repeated'));
with ranked as (
  select id, row_number() over (partition by user_id, character_id order by awarded_at desc, id desc) as position
  from public.sticker_awards
)
update public.sticker_awards awards
set album_section = case when ranked.position = 1 then 'pasted' else 'repeated' end
from ranked
where ranked.id = awards.id;

create table if not exists public.sticker_claim_history (
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id text not null,
  edition_fingerprint text not null,
  first_claimed_at timestamptz not null default now(),
  primary key (user_id, character_id, edition_fingerprint)
);
insert into public.sticker_claim_history(user_id, character_id, edition_fingerprint, first_claimed_at)
select user_id, character_id, edition_fingerprint, min(awarded_at)
from public.sticker_awards
group by user_id, character_id, edition_fingerprint
on conflict (user_id, character_id, edition_fingerprint) do nothing;
alter table public.sticker_claim_history enable row level security;
drop policy if exists "users read own sticker claim history" on public.sticker_claim_history;
create policy "users read own sticker claim history" on public.sticker_claim_history for select using (auth.uid() = user_id);

create table if not exists public.sticker_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  character_id text not null,
  character_name text not null,
  edition_fingerprint text not null,
  request_type text not null check (request_type in ('gift', 'trade')),
  offered_award_id bigint references public.sticker_awards(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (requester_id <> owner_id),
  check (request_type = 'gift' or offered_award_id is not null or status <> 'pending')
);
alter table public.sticker_requests drop constraint if exists sticker_requests_check1;
alter table public.sticker_requests add constraint sticker_requests_check1 check (
  request_type = 'gift' or offered_award_id is not null or status <> 'pending'
);
alter table public.sticker_requests add column if not exists offered_award_id_2 bigint references public.sticker_awards(id) on delete set null;
alter table public.sticker_awards add column if not exists requests_blocked boolean not null default false;
create index if not exists sticker_requests_owner_idx on public.sticker_requests(owner_id, status, created_at desc);
create index if not exists sticker_requests_requester_idx on public.sticker_requests(requester_id, status, created_at desc);
create index if not exists sticker_requests_pending_owner_idx on public.sticker_requests(owner_id, created_at desc) where status = 'pending';

alter table public.sticker_awards enable row level security;
do $$
begin
  alter publication supabase_realtime add table public.sticker_awards;
exception when duplicate_object then
  null;
end;
$$;
alter table public.sticker_requests enable row level security;
drop policy if exists "stickers are visible on accessible profiles" on public.sticker_awards;
drop policy if exists "users read their sticker requests" on public.sticker_requests;
create policy "stickers are visible on accessible profiles" on public.sticker_awards
  for select using (
    auth.uid() = user_id
    or public.is_admin()
    or (
      album_section = 'pasted'
      and (auth.uid() is null or not public.is_blocked_between(user_id))
    )
  );
create policy "users read their sticker requests" on public.sticker_requests
  for select using (auth.uid() = requester_id or auth.uid() = owner_id);

create or replace function public.claim_character_sticker(
  p_character_id text,
  p_character_name text,
  p_publisher_name text,
  p_edition_fingerprint text,
  p_edition_ids jsonb,
  p_cover_item_id text,
  p_cover_url text
)
returns public.sticker_awards
language plpgsql security definer set search_path = public
as $$
declare
  v_award public.sticker_awards;
  v_completed integer;
  v_total integer;
  v_roll integer;
  v_existing public.sticker_awards;
  v_previous public.sticker_awards;
  v_previous_2 public.sticker_awards;
  v_cover_item_id text;
  v_cover_url text;
begin
  if auth.uid() is null then raise exception 'É preciso estar autenticado'; end if;
  -- Impede duas cargas simultâneas de concederem a mesma figurinha.
  perform pg_advisory_xact_lock(hashtext(auth.uid()::text || ':' || p_character_id || ':' || p_edition_fingerprint));
  if nullif(trim(p_character_id), '') is null or nullif(trim(p_character_name), '') is null
    or nullif(trim(p_publisher_name), '') is null or nullif(trim(p_edition_fingerprint), '') is null
    or nullif(trim(p_cover_item_id), '') is null or nullif(trim(p_cover_url), '') is null
    or jsonb_typeof(p_edition_ids) <> 'array' or jsonb_array_length(p_edition_ids) = 0
  then raise exception 'Dados da figurinha inválidos'; end if;
  if p_cover_url !~ '^https://|^data:image/' then raise exception 'Capa da figurinha inválida'; end if;

  select count(*) into v_total from jsonb_array_elements_text(p_edition_ids);
  select count(*) into v_completed
  from public.reading_progress progress
  where progress.user_id = auth.uid()
    and progress.completed
    and progress.item_id in (select value from jsonb_array_elements_text(p_edition_ids));
  if v_total <> v_completed then raise exception 'Todas as edições do personagem precisam estar lidas'; end if;
  if exists (select 1 from public.sticker_awards where user_id = auth.uid() and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint) then
    select * into v_award from public.sticker_awards where user_id = auth.uid() and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint limit 1;
    return v_award;
  end if;
  if exists (select 1 from public.sticker_claim_history where user_id = auth.uid() and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint) then
    raise exception 'Esta versão da figurinha já foi conquistada; aguarde uma nova edição do personagem';
  end if;

  v_roll := floor(random() * 100)::integer;
  v_cover_item_id := p_cover_item_id;
  v_cover_url := p_cover_url;
  select * into v_existing
  from public.sticker_awards
  where user_id = auth.uid() and character_id = p_character_id
  order by awarded_at desc, id desc
  limit 1;
  select * into v_previous
  from public.sticker_awards
  where user_id = auth.uid() and character_id = p_character_id
  order by awarded_at desc, id desc
  offset 0 limit 1;
  select * into v_previous_2
  from public.sticker_awards
  where user_id = auth.uid() and character_id = p_character_id
  order by awarded_at desc, id desc
  offset 1 limit 1;
  if v_existing.id is not null
    and not (v_previous.id is not null and v_previous_2.id is not null and v_previous.cover_url = v_previous_2.cover_url)
    and random() < 0.70
  then
    v_cover_item_id := v_existing.cover_item_id;
    v_cover_url := v_existing.cover_url;
  end if;
  if v_previous.id is not null and v_previous_2.id is not null
    and v_previous.cover_url = v_previous_2.cover_url
    and v_cover_url = v_previous.cover_url
  then
    raise exception 'A mesma imagem não pode sair três vezes seguidas';
  end if;
  insert into public.sticker_claim_history(user_id, character_id, edition_fingerprint)
  values (auth.uid(), p_character_id, p_edition_fingerprint);
  insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section)
  values (auth.uid(), p_character_id, left(trim(p_character_name), 160), left(trim(p_publisher_name), 160), left(trim(p_edition_fingerprint), 500), left(trim(v_cover_item_id), 200), left(trim(v_cover_url), 2000), case when v_roll < 2 then 'gold' when v_roll < 7 then 'silver' when v_roll < 17 then 'creased' when v_roll < 35 then 'torn' else 'standard' end, case when exists (select 1 from public.sticker_awards where user_id = auth.uid() and character_id = p_character_id and album_section = 'pasted') then 'repeated' else 'pasted' end)
  returning * into v_award;
  return v_award;
end;
$$;
grant execute on function public.claim_character_sticker(text, text, text, text, jsonb, text, text) to authenticated;

create or replace function public.create_sticker_request(
  p_owner_id uuid,
  p_character_id text,
  p_character_name text,
  p_edition_fingerprint text,
  p_request_type text,
  p_offered_award_id bigint default null
)
returns public.sticker_requests
language plpgsql security definer set search_path = public
as $$
declare
  v_request public.sticker_requests;
  v_owner_username text;
begin
  if auth.uid() is null or p_owner_id is null or p_owner_id = auth.uid() then raise exception 'Pedido inválido'; end if;
  if p_request_type not in ('gift', 'trade') then raise exception 'Tipo de pedido inválido'; end if;
  -- Mantém a primeira oferta preenchida mesmo se o cliente enviar apenas
  -- a segunda posição por causa de estado antigo do seletor visual.
  if p_request_type = 'trade' and p_offered_award_id is null and p_offered_award_id_2 is not null then
    p_offered_award_id := p_offered_award_id_2;
    p_offered_award_id_2 := null;
  end if;
  if (select count(*) from public.sticker_requests where owner_id = p_owner_id and status = 'pending') >= 50 then raise exception 'Este álbum atingiu o limite de 50 pedidos pendentes'; end if;
  if (select count(*) from public.sticker_requests where requester_id = auth.uid() and status = 'pending') >= 20 then raise exception 'Você atingiu o limite de 20 pedidos pendentes'; end if;
  if public.is_blocked_between(p_owner_id) then raise exception 'Este perfil não aceita interações com você'; end if;
  if not exists (select 1 from public.profiles where id = p_owner_id and allow_sticker_requests) then raise exception 'Este usuário bloqueou pedidos de figurinhas'; end if;
  if exists (select 1 from public.sticker_awards where user_id = auth.uid() and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint) then raise exception 'Você já possui esta figurinha'; end if;
  if not exists (select 1 from public.sticker_awards where user_id = p_owner_id and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint and not requests_blocked) then raise exception 'Esta figurinha não aceita solicitações'; end if;
  if p_request_type = 'trade' and not exists (select 1 from public.sticker_awards where id = p_offered_award_id and user_id = auth.uid()) then raise exception 'Escolha uma figurinha sua para oferecer'; end if;
  if exists (select 1 from public.sticker_requests where requester_id = auth.uid() and owner_id = p_owner_id and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint and status = 'pending') then raise exception 'Você já enviou este pedido'; end if;
  insert into public.sticker_requests(requester_id, owner_id, character_id, character_name, edition_fingerprint, request_type, offered_award_id)
  values (auth.uid(), p_owner_id, left(trim(p_character_id), 160), left(trim(p_character_name), 160), left(trim(p_edition_fingerprint), 500), p_request_type, case when p_request_type = 'trade' then p_offered_award_id else null end)
  returning * into v_request;
  select username into v_owner_username from public.profiles where id = p_owner_id;
  perform public.create_notification(p_owner_id, 'sticker_request', case when p_request_type = 'trade' then 'Nova proposta de troca' else 'Pedido de figurinha' end, case when p_request_type = 'trade' then 'Alguém quer trocar uma figurinha pela sua figurinha de ' || left(trim(p_character_name), 160) || '.' else 'Alguém pediu sua figurinha de ' || left(trim(p_character_name), 160) || '.' end, auth.uid(), '?perfil=' || coalesce(v_owner_username, '') || '&album=1', jsonb_build_object('request_id', v_request.id, 'character_id', p_character_id, 'request_type', p_request_type));
  return v_request;
end;
$$;
grant execute on function public.create_sticker_request(uuid, text, text, text, text, bigint) to authenticated;

create or replace function public.respond_sticker_request(p_request_id bigint, p_status text)
returns public.sticker_requests
language plpgsql security definer set search_path = public
as $$
declare
  v_request public.sticker_requests;
  v_target public.sticker_awards;
  v_offer public.sticker_awards;
begin
  if auth.uid() is null or p_status not in ('accepted', 'declined') then raise exception 'Resposta inválida'; end if;
  select * into v_request from public.sticker_requests where id = p_request_id and owner_id = auth.uid() and status = 'pending' for update;
  if not found then raise exception 'Pedido não encontrado ou já respondido'; end if;
  if p_status = 'accepted' then
    select * into v_target from public.sticker_awards where user_id = v_request.owner_id and character_id = v_request.character_id and edition_fingerprint = v_request.edition_fingerprint order by awarded_at desc, id desc limit 1 for update;
    if not found then raise exception 'A figurinha solicitada não está mais disponível'; end if;
    if v_request.request_type = 'gift' then
      if exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and edition_fingerprint = v_target.edition_fingerprint) then raise exception 'A pessoa já possui esta figurinha'; end if;
      delete from public.sticker_awards where id = v_target.id;
      insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity)
      values (v_request.requester_id, v_target.character_id, v_target.character_name, v_target.publisher_name, v_target.edition_fingerprint, v_target.cover_item_id, v_target.cover_url, v_target.rarity);
    else
      select * into v_offer from public.sticker_awards where id = v_request.offered_award_id and user_id = v_request.requester_id for update;
      if not found then raise exception 'A figurinha oferecida não está mais disponível'; end if;
      if exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and edition_fingerprint = v_target.edition_fingerprint) then raise exception 'A pessoa já possui esta figurinha'; end if;
      if exists (select 1 from public.sticker_awards where user_id = v_request.owner_id and character_id = v_offer.character_id and edition_fingerprint = v_offer.edition_fingerprint) then raise exception 'Você já possui a figurinha oferecida'; end if;
      delete from public.sticker_awards where id in (v_target.id, v_offer.id);
      insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity)
      values (v_request.requester_id, v_target.character_id, v_target.character_name, v_target.publisher_name, v_target.edition_fingerprint, v_target.cover_item_id, v_target.cover_url, v_target.rarity),
             (v_request.owner_id, v_offer.character_id, v_offer.character_name, v_offer.publisher_name, v_offer.edition_fingerprint, v_offer.cover_item_id, v_offer.cover_url, v_offer.rarity);
    end if;
  end if;
  update public.sticker_requests set status = p_status, resolved_at = now() where id = v_request.id returning * into v_request;
  perform public.create_notification(v_request.requester_id, 'sticker_request_' || p_status, case when p_status = 'accepted' then 'Pedido de figurinha aceito' else 'Pedido de figurinha recusado' end, case when p_status = 'accepted' then 'Sua solicitação de ' || v_request.character_name || ' foi concluída.' else 'Sua solicitação de ' || v_request.character_name || ' foi recusada.' end, auth.uid(), '?album=1', jsonb_build_object('request_id', v_request.id, 'character_id', v_request.character_id));
  return v_request;
end;
$$;
grant execute on function public.respond_sticker_request(bigint, text) to authenticated;

-- Reforça a mesma regra no caminho de doação, inclusive para administradores.
create or replace function public.transfer_sticker_award(p_recipient_id uuid, p_award_id bigint)
returns public.sticker_awards language plpgsql security definer set search_path = public
as $$
declare v_character_id text;
begin
  select character_id into v_character_id from public.sticker_awards where id = p_award_id and user_id = auth.uid();
  if v_character_id is null then raise exception 'Figurinha não encontrada'; end if;
  if exists (select 1 from public.sticker_slot_preferences where user_id = p_recipient_id and character_id = v_character_id and blocked) then
    raise exception 'Este slot não aceita doações';
  end if;
  return public.donate_sticker_award(p_recipient_id, p_award_id);
end;
$$;
grant execute on function public.transfer_sticker_award(uuid, bigint) to authenticated;

-- Proteção visual por slot: também funciona quando o personagem ainda está vazio.
create table if not exists public.sticker_slot_preferences (
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id text not null,
  blocked boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, character_id)
);
alter table public.sticker_slot_preferences enable row level security;
do $$
begin
  alter publication supabase_realtime add table public.sticker_slot_preferences;
exception when duplicate_object then
  null;
end;
$$;
drop policy if exists "sticker slot preferences are public" on public.sticker_slot_preferences;
drop policy if exists "users manage own sticker slot preferences" on public.sticker_slot_preferences;
create policy "sticker slot preferences are public" on public.sticker_slot_preferences for select using (true);
create policy "users manage own sticker slot preferences" on public.sticker_slot_preferences for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.set_sticker_slot_gum(p_character_id text, p_award_id bigint default null, p_blocked boolean default true)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null or nullif(trim(p_character_id), '') is null then raise exception 'Slot inválido'; end if;
  if p_award_id is not null then
    update public.sticker_awards
    set requests_blocked = coalesce(p_blocked, false)
    where id = p_award_id and user_id = auth.uid() and character_id = p_character_id;
    if not found then raise exception 'Figurinha não encontrada'; end if;
    delete from public.sticker_slot_preferences where user_id = auth.uid() and character_id = p_character_id;
  elsif coalesce(p_blocked, false) then
    insert into public.sticker_slot_preferences(user_id, character_id, blocked, updated_at)
    values (auth.uid(), left(trim(p_character_id), 160), true, now())
    on conflict (user_id, character_id) do update set blocked = true, updated_at = now();
  else
    delete from public.sticker_slot_preferences where user_id = auth.uid() and character_id = p_character_id;
  end if;
end;
$$;
grant execute on function public.set_sticker_slot_gum(text, bigint, boolean) to authenticated;

-- Visitantes autenticados podem colar um chiclete no álbum de outra pessoa.
-- A remoção continua restrita ao dono e usa a função de três argumentos acima.
create or replace function public.set_sticker_slot_gum(p_owner_id uuid, p_character_id text, p_award_id bigint default null)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null or p_owner_id is null or nullif(trim(p_character_id), '') is null then
    raise exception 'Slot inválido';
  end if;
  if p_owner_id = auth.uid() then
    raise exception 'Use o controle do próprio álbum para remover o chiclete';
  end if;
  if not exists (select 1 from public.profiles where id = p_owner_id) then
    raise exception 'Álbum não encontrado';
  end if;
  if p_award_id is not null then
    update public.sticker_awards
    set requests_blocked = true
    where id = p_award_id and user_id = p_owner_id and character_id = p_character_id;
    if not found then raise exception 'Figurinha não encontrada'; end if;
    delete from public.sticker_slot_preferences where user_id = p_owner_id and character_id = p_character_id;
  else
    insert into public.sticker_slot_preferences(user_id, character_id, blocked, updated_at)
    values (p_owner_id, left(trim(p_character_id), 160), true, now())
    on conflict (user_id, character_id) do update set blocked = true, updated_at = now();
  end if;
end;
$$;
grant execute on function public.set_sticker_slot_gum(uuid, text, bigint) to authenticated;

create or replace function public.set_sticker_slot_gum(p_owner_id uuid, p_character_id text, p_award_id bigint default null)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_was_blocked boolean := false;
  v_username text;
begin
  if auth.uid() is null or p_owner_id is null or nullif(trim(p_character_id), '') is null then raise exception 'Slot invalido'; end if;
  if p_owner_id = auth.uid() then raise exception 'Use o controle do proprio album para remover o chiclete'; end if;
  select username into v_username from public.profiles where id = p_owner_id;
  if v_username is null then raise exception 'Album nao encontrado'; end if;
  if p_award_id is not null then
    select coalesce(requests_blocked, false) into v_was_blocked from public.sticker_awards where id = p_award_id and user_id = p_owner_id and character_id = p_character_id;
    update public.sticker_awards set requests_blocked = true where id = p_award_id and user_id = p_owner_id and character_id = p_character_id;
    if not found then raise exception 'Figurinha nao encontrada'; end if;
    delete from public.sticker_slot_preferences where user_id = p_owner_id and character_id = p_character_id;
  else
    select coalesce(blocked, false) into v_was_blocked from public.sticker_slot_preferences where user_id = p_owner_id and character_id = p_character_id;
    insert into public.sticker_slot_preferences(user_id, character_id, blocked, updated_at) values (p_owner_id, left(trim(p_character_id), 160), true, now()) on conflict (user_id, character_id) do update set blocked = true, updated_at = now();
  end if;
  if not coalesce(v_was_blocked, false) then
    perform public.create_notification(p_owner_id, 'sticker_gum', 'Chiclete colado no seu album', 'Alguem colocou um chiclete em um slot do seu album.', auth.uid(), '?perfil=' || v_username || '&album=1', jsonb_build_object('character_id', p_character_id, 'award_id', p_award_id));
  end if;
end;
$$;
grant execute on function public.set_sticker_slot_gum(uuid, text, bigint) to authenticated;

notify pgrst, 'reload schema';

create or replace function public.prevent_blocked_sticker_requests()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if exists (
    select 1 from public.sticker_slot_preferences
    where user_id = new.owner_id and character_id = new.character_id and blocked
  ) then
    raise exception 'Este slot não aceita pedidos ou trocas';
  end if;
  return new;
end;
$$;
drop trigger if exists prevent_blocked_sticker_requests_trigger on public.sticker_requests;
create trigger prevent_blocked_sticker_requests_trigger
before insert on public.sticker_requests
for each row execute function public.prevent_blocked_sticker_requests();

-- Permite trocas de até duas figurinhas por uma, mantendo os pedidos antigos.
drop function if exists public.create_sticker_request(uuid, text, text, text, text, bigint, bigint);
create or replace function public.create_sticker_request(
  p_owner_id uuid,
  p_character_id text,
  p_character_name text,
  p_edition_fingerprint text,
  p_request_type text,
  p_offered_award_id bigint default null,
  p_offered_award_id_2 bigint default null
)
returns public.sticker_requests
language plpgsql security definer set search_path = public
as $$
declare
  v_request public.sticker_requests;
  v_owner_username text;
begin
  if auth.uid() is null or p_owner_id is null or p_owner_id = auth.uid() then raise exception 'Pedido inválido'; end if;
  if p_request_type not in ('gift', 'trade') then raise exception 'Tipo de pedido inválido'; end if;
  if (select count(*) from public.sticker_requests where owner_id = p_owner_id and status = 'pending') >= 50 then raise exception 'Este álbum atingiu o limite de 50 pedidos pendentes'; end if;
  if (select count(*) from public.sticker_requests where requester_id = auth.uid() and status = 'pending') >= 20 then raise exception 'Você atingiu o limite de 20 pedidos pendentes'; end if;
  if public.is_blocked_between(p_owner_id) then raise exception 'Este perfil não aceita interações com você'; end if;
  if not exists (select 1 from public.profiles where id = p_owner_id and allow_sticker_requests) then raise exception 'Este usuário bloqueou pedidos de figurinhas'; end if;
  if exists (select 1 from public.sticker_awards where user_id = auth.uid() and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint) then raise exception 'Você já possui esta figurinha'; end if;
  if not exists (select 1 from public.sticker_awards where user_id = p_owner_id and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint and not requests_blocked) then raise exception 'Esta figurinha não aceita solicitações'; end if;
  if p_request_type = 'trade' and p_offered_award_id is null then raise exception 'Escolha uma figurinha para oferecer'; end if;
  if p_request_type = 'gift' and (p_offered_award_id is not null or p_offered_award_id_2 is not null) then raise exception 'Pedido de doação não pode oferecer figurinhas'; end if;
  if p_offered_award_id_2 is not null and p_offered_award_id_2 = p_offered_award_id then raise exception 'Escolha figurinhas diferentes'; end if;
  if p_request_type = 'trade' and not exists (select 1 from public.sticker_awards where id = p_offered_award_id and user_id = auth.uid()) then raise exception 'A primeira figurinha oferecida não está disponível'; end if;
  if p_offered_award_id_2 is not null and not exists (select 1 from public.sticker_awards where id = p_offered_award_id_2 and user_id = auth.uid()) then raise exception 'A segunda figurinha oferecida não está disponível'; end if;
  if exists (select 1 from public.sticker_requests where requester_id = auth.uid() and owner_id = p_owner_id and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint and status = 'pending') then raise exception 'Você já enviou este pedido'; end if;
  insert into public.sticker_requests(requester_id, owner_id, character_id, character_name, edition_fingerprint, request_type, offered_award_id, offered_award_id_2)
  values (auth.uid(), p_owner_id, left(trim(p_character_id), 160), left(trim(p_character_name), 160), left(trim(p_edition_fingerprint), 500), p_request_type, case when p_request_type = 'trade' then p_offered_award_id else null end, case when p_request_type = 'trade' then p_offered_award_id_2 else null end)
  returning * into v_request;
  select username into v_owner_username from public.profiles where id = p_owner_id;
  perform public.create_notification(p_owner_id, 'sticker_request', 'Nova proposta de troca', 'Alguém enviou uma proposta de troca por sua figurinha de ' || left(trim(p_character_name), 160) || '.', auth.uid(), '?perfil=' || coalesce(v_owner_username, '') || '&album=1', jsonb_build_object('request_id', v_request.id, 'character_id', p_character_id, 'request_type', p_request_type, 'offered_count', case when p_offered_award_id_2 is null then 1 else 2 end));
  return v_request;
end;
$$;
grant execute on function public.create_sticker_request(uuid, text, text, text, text, bigint, bigint) to authenticated;
drop function if exists public.create_sticker_request(uuid, text, text, text, text, bigint);
notify pgrst, 'reload schema';

create or replace function public.set_sticker_request_preference(p_allowed boolean)
returns void language sql security definer set search_path = public
as $$ update public.profiles set allow_sticker_requests = coalesce(p_allowed, true) where id = auth.uid() $$;
grant execute on function public.set_sticker_request_preference(boolean) to authenticated;

create or replace function public.set_sticker_award_lock(p_award_id bigint, p_blocked boolean)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'É preciso estar autenticado'; end if;
  update public.sticker_awards
  set requests_blocked = coalesce(p_blocked, false)
  where id = p_award_id and user_id = auth.uid();
  if not found then raise exception 'Figurinha não encontrada'; end if;
end;
$$;
grant execute on function public.set_sticker_award_lock(bigint, boolean) to authenticated;

create or replace function public.set_sticker_album_section(p_award_id bigint, p_section text)
returns public.sticker_awards
language plpgsql security definer set search_path = public
as $$
declare
  v_award public.sticker_awards;
  v_current public.sticker_awards;
begin
  if auth.uid() is null or p_section not in ('pasted', 'repeated') then raise exception 'Seção do álbum inválida'; end if;
  select * into v_award from public.sticker_awards where id = p_award_id and user_id = auth.uid() for update;
  if not found then raise exception 'Figurinha não encontrada'; end if;
  if p_section = 'pasted' then
    select * into v_current
    from public.sticker_awards
    where user_id = auth.uid()
      and character_id = v_award.character_id
      and album_section = 'pasted'
      and id <> v_award.id
    order by awarded_at desc, id desc
    limit 1
    for update;
    if v_current.id is not null then
      update public.sticker_awards set album_section = 'repeated' where id = v_current.id;
    end if;
  end if;
  update public.sticker_awards set album_section = p_section where id = v_award.id returning * into v_award;
  return v_award;
end;
$$;
grant execute on function public.set_sticker_album_section(bigint, text) to authenticated;

create or replace function public.discard_repeated_sticker(p_award_id bigint)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'É preciso estar autenticado'; end if;
  delete from public.sticker_awards
  where id = p_award_id
    and user_id = auth.uid()
    and album_section = 'repeated';
  if not found then raise exception 'Só é possível descartar figurinhas repetidas suas'; end if;
  return true;
end;
$$;
grant execute on function public.discard_repeated_sticker(bigint) to authenticated;

create or replace function public.admin_discard_sticker_award(p_award_id bigint)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem descartar figurinhas de outros álbuns';
  end if;
  delete from public.sticker_awards where id = p_award_id;
  if not found then raise exception 'Figurinha não encontrada'; end if;
  return true;
end;
$$;
grant execute on function public.admin_discard_sticker_award(bigint) to authenticated;

create or replace function public.admin_donate_sticker(
  p_recipient_id uuid,
  p_character_id text,
  p_character_name text,
  p_publisher_name text,
  p_edition_fingerprint text,
  p_edition_ids jsonb,
  p_cover_item_id text,
  p_cover_url text,
  p_rarity text
)
returns public.sticker_awards
language plpgsql security definer set search_path = public
as $$
declare
  v_result public.sticker_awards;
  v_existing public.sticker_awards;
  v_username text;
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem conceder figurinhas diretamente'; end if;
  if p_recipient_id is null or p_recipient_id = auth.uid() then raise exception 'Destinatário inválido'; end if;
  if p_rarity not in ('standard', 'torn', 'creased', 'silver', 'gold') then raise exception 'Raridade inválida'; end if;
  if nullif(trim(p_character_id), '') is null or nullif(trim(p_character_name), '') is null
    or nullif(trim(p_publisher_name), '') is null or nullif(trim(p_edition_fingerprint), '') is null
    or nullif(trim(p_cover_item_id), '') is null or nullif(trim(p_cover_url), '') is null
    or jsonb_typeof(p_edition_ids) <> 'array' or jsonb_array_length(p_edition_ids) = 0
    or p_cover_url !~ '^https://|^data:image/' then raise exception 'Dados da figurinha inválidos'; end if;
  select username into v_username from public.profiles where id = p_recipient_id;
  if v_username is null then raise exception 'Usuário não encontrado'; end if;
  if exists (select 1 from public.sticker_slot_preferences where user_id = p_recipient_id and character_id = p_character_id and blocked) then raise exception 'Este slot não aceita doações'; end if;
  if exists (select 1 from public.sticker_awards where user_id = p_recipient_id and character_id = p_character_id and album_section = 'pasted') then
    raise exception 'Essa pessoa já possui uma figurinha colada deste personagem';
  end if;
  select * into v_existing from public.sticker_awards
  where user_id = p_recipient_id and character_id = p_character_id and edition_fingerprint = p_edition_fingerprint
  for update;
  insert into public.sticker_claim_history(user_id, character_id, edition_fingerprint)
  values (p_recipient_id, p_character_id, p_edition_fingerprint)
  on conflict (user_id, character_id, edition_fingerprint) do nothing;
  if v_existing.id is not null then
    update public.sticker_awards
    set character_name = left(trim(p_character_name), 160), publisher_name = left(trim(p_publisher_name), 160), cover_item_id = left(trim(p_cover_item_id), 200), cover_url = left(trim(p_cover_url), 2000), rarity = p_rarity, album_section = 'pasted'
    where id = v_existing.id
    returning * into v_result;
  else
    insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section)
    values (p_recipient_id, p_character_id, left(trim(p_character_name), 160), left(trim(p_publisher_name), 160), left(trim(p_edition_fingerprint), 500), left(trim(p_cover_item_id), 200), left(trim(p_cover_url), 2000), p_rarity, 'pasted')
    returning * into v_result;
  end if;
  perform public.create_notification(p_recipient_id, 'sticker_admin_donation', 'Você recebeu uma figurinha', 'Um administrador adicionou uma figurinha de ' || v_result.character_name || ' ao seu álbum.', auth.uid(), '?perfil=' || v_username || '&album=1', jsonb_build_object('character_id', v_result.character_id, 'rarity', v_result.rarity));
  return v_result;
end;
$$;
grant execute on function public.admin_donate_sticker(uuid, text, text, text, text, jsonb, text, text, text) to authenticated;

create or replace function public.donate_sticker_award(p_recipient_id uuid, p_award_id bigint)
returns public.sticker_awards
language plpgsql security definer set search_path = public
as $$
declare
  v_award public.sticker_awards;
  v_result public.sticker_awards;
  v_existing public.sticker_awards;
  v_recipient_username text;
begin
  if auth.uid() is null or p_recipient_id is null or p_recipient_id = auth.uid() then
    raise exception 'Doação inválida';
  end if;
  select * into v_award
  from public.sticker_awards
  where id = p_award_id and user_id = auth.uid()
  for update;
  if not found then raise exception 'Figurinha não encontrada'; end if;
  select username into v_recipient_username from public.profiles where id = p_recipient_id;
  if v_recipient_username is null then raise exception 'Usuário não encontrado'; end if;
  select * into v_existing from public.sticker_awards
  where user_id = p_recipient_id and character_id = v_award.character_id and edition_fingerprint = v_award.edition_fingerprint
  for update;
  update public.sticker_requests
  set status = 'cancelled', resolved_at = now()
  where status = 'pending'
    and (offered_award_id = v_award.id or offered_award_id_2 = v_award.id);
  delete from public.sticker_awards where id = v_award.id;
  if v_existing.id is not null then
    update public.sticker_awards set character_name = v_award.character_name, publisher_name = v_award.publisher_name, cover_item_id = v_award.cover_item_id, cover_url = v_award.cover_url, rarity = v_award.rarity
    where id = v_existing.id
    returning * into v_result;
  else
    insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section)
    values (p_recipient_id, v_award.character_id, v_award.character_name, v_award.publisher_name, v_award.edition_fingerprint, v_award.cover_item_id, v_award.cover_url, v_award.rarity, case when exists (select 1 from public.sticker_awards where user_id = p_recipient_id and character_id = v_award.character_id and album_section = 'pasted') then 'repeated' else 'pasted' end)
    returning * into v_result;
  end if;
  perform public.create_notification(
    p_recipient_id,
    'sticker_donation',
    'Você recebeu uma figurinha',
    '@' || coalesce((select username from public.profiles where id = auth.uid()), 'alguém') || ' doou uma figurinha de ' || v_award.character_name || ' para o seu álbum.',
    auth.uid(),
    '?perfil=' || v_recipient_username || '&album=1',
    jsonb_build_object('character_id', v_award.character_id, 'award_id', v_result.id)
  );
  return v_result;
end;
$$;
grant execute on function public.donate_sticker_award(uuid, bigint) to authenticated;

create or replace function public.transfer_sticker_award(p_recipient_id uuid, p_award_id bigint)
returns public.sticker_awards
language plpgsql security definer set search_path = public
as $$
declare v_character_id text;
begin
  select character_id into v_character_id from public.sticker_awards where id = p_award_id and user_id = auth.uid();
  if v_character_id is null then raise exception 'Figurinha não encontrada'; end if;
  if exists (select 1 from public.sticker_slot_preferences where user_id = p_recipient_id and character_id = v_character_id and blocked) then
    raise exception 'Este slot não aceita doações';
  end if;
  return public.donate_sticker_award(p_recipient_id, p_award_id);
end;
$$;
grant execute on function public.transfer_sticker_award(uuid, bigint) to authenticated;

create or replace function public.respond_sticker_request(p_request_id bigint, p_status text)
returns public.sticker_requests
language plpgsql security definer set search_path = public
as $$
declare
  v_request public.sticker_requests;
  v_target public.sticker_awards;
  v_offer public.sticker_awards;
  v_offer2 public.sticker_awards;
begin
  if auth.uid() is null or p_status not in ('accepted', 'declined') then raise exception 'Resposta inválida'; end if;
  select * into v_request from public.sticker_requests where id = p_request_id and owner_id = auth.uid() and status = 'pending' for update;
  if not found then raise exception 'Pedido não encontrado ou já respondido'; end if;
  if p_status = 'accepted' then
    select * into v_target from public.sticker_awards where user_id = v_request.owner_id and character_id = v_request.character_id and edition_fingerprint = v_request.edition_fingerprint order by awarded_at desc, id desc limit 1 for update;
    if not found then raise exception 'A figurinha solicitada não está mais disponível'; end if;
    if v_request.request_type = 'gift' then
      if exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and edition_fingerprint = v_target.edition_fingerprint) then raise exception 'A pessoa já possui esta figurinha'; end if;
      delete from public.sticker_awards where id = v_target.id;
      insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section) values (v_request.requester_id, v_target.character_id, v_target.character_name, v_target.publisher_name, v_target.edition_fingerprint, v_target.cover_item_id, v_target.cover_url, v_target.rarity, case when exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and album_section = 'pasted') then 'repeated' else 'pasted' end);
    else
      select * into v_offer from public.sticker_awards where id = v_request.offered_award_id and user_id = v_request.requester_id for update;
      if not found then raise exception 'A figurinha oferecida não está mais disponível'; end if;
      if v_request.offered_award_id_2 is not null then
        select * into v_offer2 from public.sticker_awards where id = v_request.offered_award_id_2 and user_id = v_request.requester_id for update;
        if not found then raise exception 'A segunda figurinha oferecida não está mais disponível'; end if;
      end if;
      if exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and edition_fingerprint = v_target.edition_fingerprint) then raise exception 'A pessoa já possui esta figurinha'; end if;
      if exists (select 1 from public.sticker_awards where user_id = v_request.owner_id and character_id = v_offer.character_id and edition_fingerprint = v_offer.edition_fingerprint) or (v_offer2.id is not null and exists (select 1 from public.sticker_awards where user_id = v_request.owner_id and character_id = v_offer2.character_id and edition_fingerprint = v_offer2.edition_fingerprint)) then raise exception 'Você já possui uma das figurinhas oferecidas'; end if;
      delete from public.sticker_awards where id in (v_target.id, v_offer.id, v_offer2.id);
      insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section) values (v_request.requester_id, v_target.character_id, v_target.character_name, v_target.publisher_name, v_target.edition_fingerprint, v_target.cover_item_id, v_target.cover_url, v_target.rarity, case when exists (select 1 from public.sticker_awards where user_id = v_request.requester_id and character_id = v_target.character_id and album_section = 'pasted') then 'repeated' else 'pasted' end);
      insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section) values (v_request.owner_id, v_offer.character_id, v_offer.character_name, v_offer.publisher_name, v_offer.edition_fingerprint, v_offer.cover_item_id, v_offer.cover_url, v_offer.rarity, case when exists (select 1 from public.sticker_awards where user_id = v_request.owner_id and character_id = v_offer.character_id and album_section = 'pasted') then 'repeated' else 'pasted' end);
      if v_offer2.id is not null then insert into public.sticker_awards(user_id, character_id, character_name, publisher_name, edition_fingerprint, cover_item_id, cover_url, rarity, album_section) values (v_request.owner_id, v_offer2.character_id, v_offer2.character_name, v_offer2.publisher_name, v_offer2.edition_fingerprint, v_offer2.cover_item_id, v_offer2.cover_url, v_offer2.rarity, case when exists (select 1 from public.sticker_awards where user_id = v_request.owner_id and character_id = v_offer2.character_id and album_section = 'pasted') then 'repeated' else 'pasted' end); end if;
    end if;
  end if;
  update public.sticker_requests set status = p_status, resolved_at = now() where id = v_request.id returning * into v_request;
  perform public.create_notification(v_request.requester_id, 'sticker_request_' || p_status, case when p_status = 'accepted' then 'Pedido de figurinha aceito' else 'Pedido de figurinha recusado' end, case when p_status = 'accepted' then 'Sua proposta de ' || v_request.character_name || ' foi concluída.' else 'Sua proposta de ' || v_request.character_name || ' foi recusada.' end, auth.uid(), '?album=1', jsonb_build_object('request_id', v_request.id, 'character_id', v_request.character_id));
  return v_request;
end;
$$;
grant execute on function public.respond_sticker_request(bigint, text) to authenticated;
