-- Moderação completa do chat: punições por sala, slow mode, denúncias e auditoria.
create table if not exists public.chat_room_settings (
  room_id text primary key references public.chat_rooms(id) on delete cascade,
  slow_mode_seconds integer not null default 0 check (slow_mode_seconds between 0 and 300),
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_room_mutes (
  room_id text not null references public.chat_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  muted_by uuid references public.profiles(id) on delete set null,
  muted_until timestamptz,
  reason text not null default '',
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);
create index if not exists chat_room_mutes_active_idx on public.chat_room_mutes(room_id, muted_until);

create table if not exists public.chat_message_reports (
  id bigint generated by default as identity primary key,
  message_id bigint,
  room_id text not null references public.chat_rooms(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid not null references public.profiles(id) on delete cascade,
  message_body text not null,
  reason text not null check (char_length(trim(reason)) between 3 and 500),
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'dismissed')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists chat_message_reports_pending_idx on public.chat_message_reports(message_id, reporter_id) where status = 'pending';
create index if not exists chat_message_reports_status_idx on public.chat_message_reports(status, created_at desc);

create table if not exists public.chat_moderation_actions (
  id bigint generated by default as identity primary key,
  room_id text references public.chat_rooms(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid references public.profiles(id) on delete set null,
  message_id bigint,
  action text not null,
  duration_until timestamptz,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists chat_moderation_actions_room_created_idx on public.chat_moderation_actions(room_id, created_at desc);

alter table public.chat_room_settings enable row level security;
alter table public.chat_room_mutes enable row level security;
alter table public.chat_message_reports enable row level security;
alter table public.chat_moderation_actions enable row level security;

drop policy if exists "chat room settings visible to members" on public.chat_room_settings;
create policy "chat room settings visible to members" on public.chat_room_settings for select using (public.can_access_chat_room(room_id));
drop policy if exists "chat room mutes visible to affected users" on public.chat_room_mutes;
create policy "chat room mutes visible to affected users" on public.chat_room_mutes for select using (auth.uid() = user_id or public.is_moderator() or public.is_chat_room_sheriff(room_id));
drop policy if exists "users report chat messages" on public.chat_message_reports;
create policy "users report chat messages" on public.chat_message_reports for insert to authenticated with check (auth.uid() = reporter_id and reporter_id <> target_id and public.can_access_chat_room(room_id));
drop policy if exists "reporters read own chat reports" on public.chat_message_reports;
create policy "reporters read own chat reports" on public.chat_message_reports for select using (auth.uid() = reporter_id or public.is_moderator());
drop policy if exists "staff review chat reports" on public.chat_message_reports;
create policy "staff review chat reports" on public.chat_message_reports for update using (public.is_moderator()) with check (public.is_moderator());
drop policy if exists "chat moderation history visible" on public.chat_moderation_actions;
create policy "chat moderation history visible" on public.chat_moderation_actions for select using (public.is_moderator() or (room_id is not null and public.is_chat_room_sheriff(room_id)));

grant select on public.chat_room_settings, public.chat_room_mutes, public.chat_message_reports, public.chat_moderation_actions to authenticated;
grant insert on public.chat_message_reports to authenticated;
grant update on public.chat_message_reports to authenticated;

create or replace function public.can_send_chat_room(p_room_id text)
returns boolean language plpgsql stable security definer set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_slow integer;
  v_last timestamptz;
begin
  select * into v_profile from public.profiles where id = auth.uid();
  if not found or v_profile.is_banned or (v_profile.silenced_until is not null and v_profile.silenced_until > now()) then return false; end if;
  if not exists (select 1 from public.chat_rooms room where room.id = p_room_id and (
    (room.access = 'public' and (room.faction_id is null or v_profile.plan in ('moderator', 'banca', 'admin') or v_profile.faction_id = room.faction_id))
    or (room.access = 'faction' and (v_profile.plan in ('moderator', 'banca', 'admin') or v_profile.faction_id = room.faction_id))
    or (room.access = 'premium' and (v_profile.plan in ('premium', 'admin') or (v_profile.plan = 'free' and public.is_legendary_event_active())))
    or (room.access = 'staff' and v_profile.plan in ('moderator', 'banca', 'admin'))
  )) then return false; end if;
  if exists (select 1 from public.chat_room_mutes where room_id = p_room_id and user_id = auth.uid() and (muted_until is null or muted_until > now())) then return false; end if;
  if v_profile.plan in ('moderator', 'banca', 'admin') then return true; end if;
  select slow_mode_seconds into v_slow from public.chat_room_settings where room_id = p_room_id;
  if coalesce(v_slow, 0) > 0 then
    select created_at into v_last from public.chat_messages where room_id = p_room_id and sender_id = auth.uid() order by created_at desc limit 1;
    if v_last is not null and v_last > now() - make_interval(secs => v_slow) then return false; end if;
  end if;
  return true;
end;
$$;

create or replace function public.set_chat_room_slow_mode(p_room_id text, p_seconds integer)
returns public.chat_room_settings language plpgsql security definer set search_path = public
as $$
declare v_row public.chat_room_settings;
begin
  if not public.is_moderator() then raise exception 'Apenas moderadores podem alterar o slow mode'; end if;
  if p_seconds not between 0 and 300 then raise exception 'O slow mode deve ficar entre 0 e 300 segundos'; end if;
  insert into public.chat_room_settings(room_id, slow_mode_seconds, updated_by) values (p_room_id, p_seconds, auth.uid())
  on conflict (room_id) do update set slow_mode_seconds = excluded.slow_mode_seconds, updated_by = excluded.updated_by, updated_at = now()
  returning * into v_row;
  insert into public.chat_moderation_actions(room_id, actor_id, action, details) values (p_room_id, auth.uid(), 'slow_mode', jsonb_build_object('seconds', p_seconds));
  return v_row;
end;
$$;

create or replace function public.moderate_chat_user(p_room_id text, p_username text, p_action text, p_duration text default '1h', p_reason text default '')
returns void language plpgsql security definer set search_path = public
as $$
declare v_target public.profiles%rowtype; v_until timestamptz; v_deleted integer := 0;
begin
  if not (public.is_moderator() or public.is_chat_room_sheriff(p_room_id)) then raise exception 'Apenas moderadores ou o xerife podem moderar esta sala'; end if;
  select * into v_target from public.profiles where lower(username) = lower(trim(p_username));
  if not found then raise exception 'Usuário não encontrado'; end if;
  if p_action = 'mute' then
    v_until := case p_duration when '10m' then now()+interval '10 minutes' when '1h' then now()+interval '1 hour' when '24h' then now()+interval '24 hours' when '7d' then now()+interval '7 days' else null end;
    insert into public.chat_room_mutes(room_id, user_id, muted_by, muted_until, reason) values (p_room_id, v_target.id, auth.uid(), v_until, left(trim(p_reason), 500))
    on conflict (room_id, user_id) do update set muted_by=excluded.muted_by, muted_until=excluded.muted_until, reason=excluded.reason, created_at=now();
  elsif p_action = 'unmute' then
    delete from public.chat_room_mutes where room_id = p_room_id and user_id = v_target.id;
  elsif p_action = 'clear_recent' then
    delete from public.chat_messages where room_id = p_room_id and sender_id = v_target.id and created_at > now() - interval '24 hours';
    get diagnostics v_deleted = row_count;
  else raise exception 'Ação de moderação inválida'; end if;
  insert into public.chat_moderation_actions(room_id, actor_id, target_id, action, duration_until, details) values (p_room_id, auth.uid(), v_target.id, p_action, v_until, jsonb_build_object('username', v_target.username, 'reason', left(trim(p_reason), 500), 'deleted_count', v_deleted));
end;
$$;

create or replace function public.get_chat_moderation_history(p_room_id text, p_limit integer default 50)
returns setof public.chat_moderation_actions language sql stable security definer set search_path = public
as $$ select * from public.chat_moderation_actions where room_id = p_room_id and (public.is_moderator() or public.is_chat_room_sheriff(p_room_id)) order by created_at desc limit least(greatest(p_limit, 1), 100) $$;

grant execute on function public.set_chat_room_slow_mode(text, integer), public.moderate_chat_user(text, text, text, text, text), public.get_chat_moderation_history(text, integer) to authenticated;

drop policy if exists "users send chat messages" on public.chat_messages;
create policy "users send chat messages" on public.chat_messages for insert with check (
  auth.uid() = sender_id and public.can_post_content('chat', body)
  and expires_at <= now() + interval '24 hours' and expires_at > now()
  and ((room_id is null and recipient_id is not null and auth.uid() <> recipient_id and not public.is_blocked_between(recipient_id) and exists (select 1 from public.profiles where id = recipient_id and allow_messages))
    or (room_id is not null and recipient_id is null and public.can_send_chat_room(room_id)))
);

notify pgrst, 'reload schema';
