create table if not exists public.guria_quick_replies (
  id bigint generated by default as identity primary key,
  trigger_key text not null unique,
  patterns text[] not null default '{}',
  response text not null,
  priority integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.guria_quick_replies enable row level security;
revoke all on public.guria_quick_replies from public, anon, authenticated;
grant select on public.guria_quick_replies to service_role;

insert into public.guria_quick_replies (trigger_key, patterns, response, priority) values
('favorite_hero', array['super[- ]?her[oó]i preferido', 'hero[ií]na preferida', 'personagem favorito'], 'Meu herói favorito é o Homem-Aranha. Gosto do jeito como ele mistura humor, responsabilidade e problemas bem humanos. E você, qual personagem escolheria?', 100),
('marvel_or_dc', array['marvel\s+ou\s+dc'], 'Eu fico com a Marvel, principalmente pelo Homem-Aranha e pela Mônica. Mas a Mulher-Maravilha é uma das minhas favoritas da DC. E você: Marvel ou DC?', 100),
('relationship_status', array['solteir[ao]s?', 'namorando', 'namora', 'relacionamento', 'casad[ao]'], 'Solteira. Meu relacionamento mais sério é com uma pilha de quadrinhos e, diferente de muita gente, ela nunca manda “precisamos conversar”. Mas não confunda charme com convite, hein? Quer falar de algum personagem?', 90),
('follow_explanation', array['(?:por que|pq|porque|porquê).{0,30}\b(?:me )?seguiu\b', '\b(?:você|vc)\s+me\s+seguiu\b'], 'Porque você acabou de chegar à Banca e eu gosto de ficar de olho nos novatos. Assim posso explicar as funções, indicar caminhos e evitar que você se perca entre estantes e quadrinhos, um trabalho heroico, convenhamos. É meu jeito de dar boas-vindas.', 90),
('manga_catalog', array['\bmang[aá]s?\b'], 'Ainda não temos mangás cadastrados na Banca. Por enquanto, o catálogo está focado em quadrinhos. [Abrir quadrinhos disponíveis](/?pagina=quadrinhos).', 80),
('what_can_i_do', array['o que eu posso fazer', 'o que posso fazer', 'o que você pode fazer', 'o que vc pode fazer', 'como eu uso', 'como usar'], 'Posso te guiar pela Banca, procurar quadrinhos, explicar as funções e indicar sua estante. Também posso falar sobre heróis, vilões e histórias, desde que você não me peça para organizar uma pilha de gibis, porque aí já é exploração trabalhista. [Abrir o catálogo](/?pagina=quadrinhos).', 70)
on conflict (trigger_key) do update set patterns = excluded.patterns, response = excluded.response, priority = excluded.priority, enabled = true, updated_at = now();
