create table if not exists public.profile_display_stickers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  award_id bigint not null references public.sticker_awards(id) on delete cascade,
  slot smallint not null check (slot between 1 and 5),
  created_at timestamptz not null default now(),
  unique (user_id, slot),
  unique (user_id, award_id)
);

create index if not exists profile_display_stickers_user_idx
  on public.profile_display_stickers(user_id, slot);

insert into public.profile_display_stickers (user_id, award_id, slot)
select profiles.id, profiles.profile_sticker_award_id, 1
from public.profiles
join public.sticker_awards on sticker_awards.id = profiles.profile_sticker_award_id
where profiles.profile_sticker_award_id is not null
  and sticker_awards.user_id = profiles.id
  and sticker_awards.album_section = 'pasted'
  and sticker_awards.cover_url is not null
on conflict do nothing;

alter table public.profile_display_stickers enable row level security;

drop policy if exists "profile display stickers are visible" on public.profile_display_stickers;
drop policy if exists "users manage own profile display stickers" on public.profile_display_stickers;

create policy "profile display stickers are visible"
  on public.profile_display_stickers for select
  using (
    auth.uid() = user_id
    or exists (
      select 1 from public.profiles
      where profiles.id = profile_display_stickers.user_id
        and profiles.profile_hidden = false
        and profiles.profile_wall_public = true
    )
  );

create policy "users manage own profile display stickers"
  on public.profile_display_stickers for all
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.sticker_awards
      where sticker_awards.id = profile_display_stickers.award_id
        and sticker_awards.user_id = auth.uid()
        and sticker_awards.album_section = 'pasted'
        and sticker_awards.cover_url is not null
    )
  );
