-- Monitoramento independente de novas edições encontradas em páginas fonte.
create table if not exists public.series_link_sources (
  id bigint generated by default as identity primary key,
  series_id text not null,
  source_url text not null check (source_url ~ '^https://'),
  provider text not null default 'blogspot',
  enabled boolean not null default true,
  last_checked_at timestamptz,
  last_content_hash text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (series_id, source_url)
);

create table if not exists public.series_link_discoveries (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.series_link_sources(id) on delete cascade,
  series_id text not null,
  issue text not null,
  title text not null,
  file_url text not null check (file_url ~ '^https://'),
  normalized_url text not null,
  source_url text not null check (source_url ~ '^https://'),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  metadata jsonb not null default '{}'::jsonb,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, normalized_url)
);

create index if not exists series_link_sources_enabled_idx on public.series_link_sources(enabled);
create index if not exists series_link_discoveries_status_idx on public.series_link_discoveries(status, created_at desc);
create index if not exists series_link_discoveries_series_idx on public.series_link_discoveries(series_id, issue);

alter table public.series_link_sources enable row level security;
alter table public.series_link_discoveries enable row level security;

drop policy if exists "staff view series link sources" on public.series_link_sources;
drop policy if exists "admins view series link sources" on public.series_link_sources;
create policy "admins view series link sources" on public.series_link_sources
  for select to authenticated using (public.is_admin());

drop policy if exists "staff view series link discoveries" on public.series_link_discoveries;
drop policy if exists "admins view series link discoveries" on public.series_link_discoveries;
drop policy if exists "admins review series link discoveries" on public.series_link_discoveries;
create policy "admins view series link discoveries" on public.series_link_discoveries
  for select to authenticated using (public.is_admin());

create policy "admins review series link discoveries" on public.series_link_discoveries
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

insert into public.series_link_sources (series_id, source_url, provider)
values ('series-shazam-2023', 'https://hqs-soquadrinhos.blogspot.com/2023/05/shazam-2023.html', 'blogspot')
on conflict (series_id, source_url) do update set provider = excluded.provider, enabled = true, updated_at = now();
