-- Eleições mensais das facções.
-- A apuração é feita no banco para que o cliente não possa fabricar votos.

create table if not exists public.faction_elections (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.faction_seasons(id) on delete cascade,
  faction_id text not null references public.factions(id) on delete cascade,
  phase text not null default 'candidacy' check (phase in ('candidacy', 'curator_vote', 'leader_vote', 'held', 'completed')),
  status text not null default 'active' check (status in ('active', 'held', 'completed')),
  candidacy_ends_at timestamptz not null,
  curator_vote_ends_at timestamptz not null,
  ends_at timestamptz not null,
  held_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, faction_id)
);

create table if not exists public.faction_election_candidates (
  election_id bigint not null references public.faction_elections(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  office text not null check (office in ('curator', 'leader')),
  pitch text not null default '' check (char_length(pitch) <= 500),
  created_at timestamptz not null default now(),
  primary key (election_id, office, user_id)
);

create table if not exists public.faction_election_votes (
  election_id bigint not null references public.faction_elections(id) on delete cascade,
  office text not null check (office in ('curator', 'leader')),
  voter_id uuid not null references public.profiles(id) on delete cascade,
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (election_id, office, voter_id)
);

create index if not exists faction_election_candidates_lookup_idx
  on public.faction_election_candidates(election_id, office, created_at);
create index if not exists faction_election_votes_lookup_idx
  on public.faction_election_votes(election_id, office, candidate_id);

alter table public.faction_elections enable row level security;
alter table public.faction_election_candidates enable row level security;
alter table public.faction_election_votes enable row level security;

drop policy if exists "faction elections are public" on public.faction_elections;
create policy "faction elections are public" on public.faction_elections for select to anon, authenticated using (true);
drop policy if exists "faction election candidates are public" on public.faction_election_candidates;
create policy "faction election candidates are public" on public.faction_election_candidates for select to anon, authenticated using (true);
drop policy if exists "users can see their faction election votes" on public.faction_election_votes;
create policy "users can see their faction election votes" on public.faction_election_votes for select to authenticated using ((select auth.uid()) = voter_id);

revoke all on public.faction_election_candidates from anon, authenticated;
grant select on public.faction_election_candidates to anon, authenticated;
revoke all on public.faction_election_votes from anon, authenticated;
revoke all on public.faction_elections from anon, authenticated;
grant select on public.faction_elections to anon, authenticated;

create or replace function public.faction_election_eligible_member(p_user_id uuid, p_faction_id text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles profile
    where profile.id = p_user_id
      and profile.faction_id = p_faction_id
      and profile.plan not in ('moderator', 'banca', 'admin')
  );
$$;

create or replace function public.ensure_faction_election(p_faction_id text)
returns public.faction_elections language plpgsql security definer set search_path = public
as $$
declare
  v_season public.faction_seasons%rowtype;
  v_election public.faction_elections%rowtype;
  v_candidacy_end timestamptz;
  v_curator_end timestamptz;
  v_member_count integer;
  v_vote_count integer;
  v_required integer;
  v_winner record;
  v_slot integer;
begin
  if auth.uid() is not null and not exists (select 1 from public.profiles where id = auth.uid() and faction_id = p_faction_id) and not public.is_moderator() then
    raise exception 'Você só pode consultar a eleição da sua facção';
  end if;
  v_season := public.current_faction_season();
  -- O calendário é proporcional à temporada real, em vez de assumir 30 dias.
  -- 65% candidatura, 20% curadores e 15% líder.
  v_candidacy_end := v_season.starts_at + ((v_season.ends_at - v_season.starts_at) * 0.65);
  v_curator_end := v_season.starts_at + ((v_season.ends_at - v_season.starts_at) * 0.85);
  insert into public.faction_elections(season_id, faction_id, candidacy_ends_at, curator_vote_ends_at, ends_at)
  values (v_season.id, p_faction_id, v_candidacy_end, v_curator_end, v_season.ends_at)
  on conflict (season_id, faction_id) do nothing;
  select * into v_election from public.faction_elections where season_id = v_season.id and faction_id = p_faction_id for update;

  if v_election.status = 'active' and v_election.phase = 'candidacy' and now() >= v_election.candidacy_ends_at then
    select count(*) into v_member_count from public.profiles where faction_id = p_faction_id and plan not in ('moderator', 'banca', 'admin');
    select count(*) into v_vote_count from public.faction_election_candidates where election_id = v_election.id and office = 'curator';
    if v_member_count < 2 or v_vote_count = 0 then
      update public.faction_elections set phase = 'held', status = 'held', held_reason = case when v_member_count < 2 then 'Poucos membros elegíveis para votar' else 'Nenhum candidato a curador' end, updated_at = now() where id = v_election.id;
      perform public.ensure_faction_leadership(p_faction_id);
    else
      update public.faction_elections set phase = 'curator_vote', updated_at = now() where id = v_election.id;
    end if;
    select * into v_election from public.faction_elections where id = v_election.id;
  end if;

  if v_election.status = 'active' and v_election.phase = 'curator_vote' and now() >= v_election.curator_vote_ends_at then
    select count(*) into v_member_count from public.profiles where faction_id = p_faction_id and plan not in ('moderator', 'banca', 'admin');
    v_required := greatest(2, ceil(v_member_count * 0.25)::integer);
    select count(distinct voter_id) into v_vote_count from public.faction_election_votes where election_id = v_election.id and office = 'curator';
    if v_vote_count < v_required then
      update public.faction_elections set phase = 'held', status = 'held', held_reason = 'O quórum da votação não foi atingido', updated_at = now() where id = v_election.id;
      perform public.ensure_faction_leadership(p_faction_id);
    else
      delete from public.faction_roles where faction_id = p_faction_id and role = 'curator';
      for v_winner in
        select candidate.user_id, row_number() over (order by count(vote.voter_id) desc, coalesce(sum(xp.xp) filter (where xp.season_id = v_election.season_id), 0) desc, profile.last_seen_at desc, candidate.user_id) as winner_slot
        from public.faction_election_candidates candidate
        join public.profiles profile on profile.id = candidate.user_id and profile.faction_id = p_faction_id and profile.plan not in ('moderator', 'banca', 'admin')
        left join public.faction_election_votes vote on vote.election_id = v_election.id and vote.office = 'curator' and vote.candidate_id = candidate.user_id
        left join public.faction_xp_events xp on xp.user_id = candidate.user_id and xp.faction_id = p_faction_id
        where candidate.election_id = v_election.id and candidate.office = 'curator'
        group by candidate.user_id, profile.last_seen_at
        order by count(vote.voter_id) desc, coalesce(sum(xp.xp) filter (where xp.season_id = v_election.season_id), 0) desc, profile.last_seen_at desc, candidate.user_id
        limit 3
      loop
        insert into public.faction_roles(user_id, faction_id, role, slot) values (v_winner.user_id, p_faction_id, 'curator', v_winner.winner_slot::integer);
        update public.profiles set plan = 'premium' where id = v_winner.user_id and plan = 'free';
      end loop;
      if (select count(*) from public.faction_roles where faction_id = p_faction_id and role = 'curator') < 2 then
        update public.faction_elections set phase = 'held', status = 'held', held_reason = 'Poucos curadores eleitos para formar o colégio', updated_at = now() where id = v_election.id;
        perform public.ensure_faction_leadership(p_faction_id);
      else
        delete from public.faction_election_candidates where election_id = v_election.id and office = 'leader';
        insert into public.faction_election_candidates(election_id, user_id, office, pitch)
        select v_election.id, user_id, 'leader', '' from public.faction_roles where faction_id = p_faction_id and role = 'curator';
        update public.faction_elections set phase = 'leader_vote', updated_at = now() where id = v_election.id;
      end if;
    end if;
    select * into v_election from public.faction_elections where id = v_election.id;
  end if;

  if v_election.status = 'active' and v_election.phase = 'leader_vote' and now() >= v_election.ends_at then
    select count(*) into v_member_count from public.faction_roles where faction_id = p_faction_id and role = 'curator';
    select count(distinct voter_id) into v_vote_count from public.faction_election_votes where election_id = v_election.id and office = 'leader';
    if v_member_count < 2 or v_vote_count < 2 then
      update public.faction_elections set phase = 'held', status = 'held', held_reason = 'O colégio de curadores não atingiu o quórum', updated_at = now() where id = v_election.id;
      perform public.ensure_faction_leadership(p_faction_id);
    else
      select candidate_id into v_winner from public.faction_election_votes where election_id = v_election.id and office = 'leader' group by candidate_id order by count(*) desc, candidate_id limit 1;
      if v_winner.candidate_id is not null then
        delete from public.faction_roles where faction_id = p_faction_id;
        insert into public.faction_roles(user_id, faction_id, role, slot) values (v_winner.candidate_id, p_faction_id, 'leader', 1);
        update public.profiles set plan = 'premium' where id = v_winner.candidate_id and plan = 'free';
        update public.faction_elections set phase = 'completed', status = 'completed', updated_at = now() where id = v_election.id;
        perform public.ensure_faction_leadership(p_faction_id);
      end if;
    end if;
    select * into v_election from public.faction_elections where id = v_election.id;
  end if;
  return v_election;
end;
$$;
grant execute on function public.ensure_faction_election(text) to authenticated;

create or replace function public.register_faction_curator_candidate(p_pitch text default '')
returns public.faction_election_candidates language plpgsql security definer set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_election public.faction_elections%rowtype;
  v_result public.faction_election_candidates%rowtype;
begin
  select * into v_profile from public.profiles where id = auth.uid();
  if v_profile.id is null or v_profile.faction_id is null or v_profile.plan in ('moderator', 'banca', 'admin') then raise exception 'Você não pode se candidatar'; end if;
  v_election := public.ensure_faction_election(v_profile.faction_id);
  if v_election.phase <> 'candidacy' or now() >= v_election.candidacy_ends_at then raise exception 'O período de candidaturas terminou'; end if;
  insert into public.faction_election_candidates(election_id, user_id, office, pitch)
  values (v_election.id, auth.uid(), 'curator', left(trim(coalesce(p_pitch, '')), 500))
  on conflict (election_id, office, user_id) do update set pitch = excluded.pitch
  returning * into v_result;
  return v_result;
end;
$$;
grant execute on function public.register_faction_curator_candidate(text) to authenticated;

create or replace function public.cast_faction_election_vote(p_election_id bigint, p_office text, p_candidate_id uuid)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_election public.faction_elections%rowtype;
  v_profile public.profiles%rowtype;
  v_allowed boolean := false;
begin
  select * into v_profile from public.profiles where id = auth.uid();
  select * into v_election from public.faction_elections where id = p_election_id;
  if v_profile.id is null or v_election.id is null then raise exception 'Eleição inválida'; end if;
  if v_election.status <> 'active' or (p_office = 'curator' and v_election.phase <> 'curator_vote') or (p_office = 'leader' and v_election.phase <> 'leader_vote') then raise exception 'Esta votação não está aberta'; end if;
  if not exists (select 1 from public.faction_election_candidates where election_id = p_election_id and office = p_office and user_id = p_candidate_id) then raise exception 'Candidato inválido'; end if;
  if p_office = 'curator' then
    v_allowed := public.faction_election_eligible_member(auth.uid(), v_election.faction_id);
  else
    v_allowed := exists (select 1 from public.faction_roles where user_id = auth.uid() and faction_id = v_election.faction_id and role = 'curator');
  end if;
  if not v_allowed then raise exception 'Você não faz parte deste colégio eleitoral'; end if;
  insert into public.faction_election_votes(election_id, office, voter_id, candidate_id)
  values (p_election_id, p_office, auth.uid(), p_candidate_id)
  on conflict (election_id, office, voter_id) do update set candidate_id = excluded.candidate_id, created_at = now();
end;
$$;
grant execute on function public.cast_faction_election_vote(bigint, text, uuid) to authenticated;

create or replace function public.get_faction_election(p_faction_id text)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  v_election public.faction_elections%rowtype;
  v_result jsonb;
begin
  v_election := public.ensure_faction_election(p_faction_id);
  select jsonb_build_object(
    'id', v_election.id,
    'season_id', v_election.season_id,
    'faction_id', v_election.faction_id,
    'phase', v_election.phase,
    'status', v_election.status,
    'candidacy_ends_at', v_election.candidacy_ends_at,
    'curator_vote_ends_at', v_election.curator_vote_ends_at,
    'ends_at', v_election.ends_at,
    'held_reason', v_election.held_reason,
    'candidates', coalesce((select jsonb_agg(jsonb_build_object('user_id', candidate.user_id, 'office', candidate.office, 'pitch', candidate.pitch) order by candidate.office, candidate.created_at) from public.faction_election_candidates candidate where candidate.election_id = v_election.id), '[]'::jsonb),
    'my_curator_vote', (select candidate_id from public.faction_election_votes where election_id = v_election.id and office = 'curator' and voter_id = auth.uid()),
    'my_leader_vote', (select candidate_id from public.faction_election_votes where election_id = v_election.id and office = 'leader' and voter_id = auth.uid())
  ) into v_result;
  return v_result;
end;
$$;
grant execute on function public.get_faction_election(text) to authenticated;

notify pgrst, 'reload schema';
