-- Guria: assistente oficial, integrada ao modelo social/chat existente.
-- A automação externa (modelo e cron) fica em Edge Functions; não há chamadas
-- de rede em triggers do Postgres.
alter table public.profiles add column if not exists is_bot boolean not null default false;
alter table public.profiles add column if not exists is_official boolean not null default false;
alter table public.profiles add column if not exists bot_type text;
alter table public.profiles add column if not exists guria_proactive_enabled boolean not null default true;
alter table public.profiles drop constraint if exists profiles_bot_type_check;
alter table public.profiles add constraint profiles_bot_type_check check (bot_type is null or bot_type in ('assistant'));
alter table public.profiles drop constraint if exists profiles_title_length_check;
alter table public.profiles add constraint profiles_title_length_check check (title is null or char_length(title) between 1 and 40);

alter table public.chat_messages add column if not exists guria_event_key text;
create unique index if not exists chat_messages_guria_event_key_idx on public.chat_messages(guria_event_key) where guria_event_key is not null;

create table if not exists public.guria_knowledge (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 240),
  summary text not null default '' check (char_length(summary) <= 4000),
  kind text not null default 'comic',
  character_name text,
  publisher text,
  authors text,
  universe text,
  saga text,
  edition text,
  source text,
  source_url text,
  language text not null default 'pt-BR',
  publication_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  search_document tsvector generated always as (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(summary,'') || ' ' || coalesce(character_name,'') || ' ' || coalesce(publisher,'') || ' ' || coalesce(authors,'') || ' ' || coalesce(universe,'') || ' ' || coalesce(saga,''))) stored
);
create index if not exists guria_knowledge_search_idx on public.guria_knowledge using gin(search_document);
create index if not exists guria_knowledge_exact_title_idx on public.guria_knowledge(lower(title));

create table if not exists public.guria_ai_jobs (
  id bigint generated by default as identity primary key,
  source_message_id bigint not null references public.chat_messages(id) on delete cascade,
  status text not null default 'queued' check (status in ('queued','processing','completed','failed')),
  provider text,
  error_code text,
  response_message_id bigint references public.chat_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  unique(source_message_id)
);
create index if not exists guria_ai_jobs_status_idx on public.guria_ai_jobs(status, created_at);
create table if not exists public.guria_ai_usage (
  usage_date date not null default current_date,
  user_id uuid not null references public.profiles(id) on delete cascade,
  request_count integer not null default 0 check (request_count >= 0),
  primary key (usage_date, user_id)
);
alter table public.guria_ai_usage enable row level security;
revoke all on public.guria_ai_usage from anon, authenticated;
create or replace function public.claim_guria_ai_quota(p_user_id uuid, p_user_limit integer default 20, p_global_limit integer default 200)
returns boolean language plpgsql security definer set search_path = public
as $$
declare v_user_count integer; v_global_count integer;
begin
  perform pg_advisory_xact_lock(hashtext('guria-ai-quota'));
  select coalesce(sum(request_count), 0) into v_global_count from public.guria_ai_usage where usage_date = current_date;
  select request_count into v_user_count from public.guria_ai_usage where usage_date = current_date and user_id = p_user_id for update;
  if coalesce(v_user_count, 0) >= greatest(p_user_limit, 0) or v_global_count >= greatest(p_global_limit, 0) then return false; end if;
  insert into public.guria_ai_usage(usage_date, user_id, request_count) values (current_date, p_user_id, 1)
  on conflict (usage_date, user_id) do update set request_count = public.guria_ai_usage.request_count + 1;
  return true;
end;
$$;
revoke execute on function public.claim_guria_ai_quota(uuid, integer, integer) from public, anon, authenticated;
grant execute on function public.claim_guria_ai_quota(uuid, integer, integer) to service_role;

create table if not exists public.guria_moderation_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  source_message_id bigint references public.chat_messages(id) on delete set null,
  category text not null check (category in ('assédio','sexual_explicito','insistencia','ameaca','coercao','odio','sexualizacao_menores')),
  risk_level text not null check (risk_level in ('baixo','medio','alto','critico')),
  rule_key text not null,
  recurrence_count integer not null default 1 check (recurrence_count > 0),
  status text not null default 'pending' check (status in ('pending','reviewed','dismissed','restricted')),
  admin_decision text,
  moderator_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique(source_message_id, rule_key)
);
create index if not exists guria_moderation_events_user_idx on public.guria_moderation_events(user_id, created_at desc);

alter table public.guria_knowledge enable row level security;
alter table public.guria_ai_jobs enable row level security;
alter table public.guria_moderation_events enable row level security;
revoke all on public.guria_knowledge, public.guria_ai_jobs, public.guria_moderation_events from anon, authenticated;
grant select on public.guria_knowledge to authenticated;
grant select on public.guria_ai_jobs to authenticated;
grant select, update on public.guria_moderation_events to authenticated;
create policy "authenticated reads Guria knowledge" on public.guria_knowledge for select to authenticated using (true);
create policy "users read own Guria jobs" on public.guria_ai_jobs for select to authenticated using (exists (select 1 from public.chat_messages m where m.id = source_message_id and auth.uid() = m.sender_id));
create policy "admins review Guria moderation" on public.guria_moderation_events for select to authenticated using (public.is_admin());
create policy "admins update Guria moderation" on public.guria_moderation_events for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage Guria knowledge" on public.guria_knowledge for all to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.protect_guria_profile_fields()
returns trigger language plpgsql set search_path = public
as $$
begin
  if current_user <> 'service_role' and not public.is_admin() and (tg_op = 'INSERT' or new.is_bot is distinct from old.is_bot or new.is_official is distinct from old.is_official or new.bot_type is distinct from old.bot_type) then
    raise exception 'Somente administradores podem alterar a identidade de um perfil oficial';
  end if;
  return new;
end;
$$;
drop trigger if exists protect_guria_profile_fields_trigger on public.profiles;
create trigger protect_guria_profile_fields_trigger before insert or update on public.profiles for each row execute procedure public.protect_guria_profile_fields();
revoke execute on function public.protect_guria_profile_fields() from public, anon, authenticated;

create or replace function public.guria_welcome_new_profile()
returns trigger language plpgsql security definer set search_path = public
as $$
declare v_guria uuid; v_message text;
begin
  select id into v_guria from public.profiles where username = 'guria' and is_bot and is_official limit 1;
  if v_guria is null or new.id = v_guria or new.is_banned then return new; end if;
  insert into public.profile_follows(follower_id, following_id) values (v_guria, new.id) on conflict do nothing;
  v_message := format('Oi, %s! Eu sou a Guria, a IA oficial e guia da Banca. Vi que você acabou de chegar e passei para dar as boas-vindas. Posso explicar como o site funciona, indicar uma leitura ou simplesmente conversar sobre quadrinhos. Por onde você quer começar?', coalesce(nullif(new.username,''),'leitor'));
  insert into public.chat_messages(sender_id, recipient_id, body, metadata, guria_event_key)
  values (v_guria, new.id, v_message, jsonb_build_object('guria_type','welcome','official_ai',true), 'welcome:' || new.id::text)
  on conflict (guria_event_key) do nothing;
  return new;
end;
$$;
drop trigger if exists guria_welcome_new_profile_trigger on public.profiles;
create trigger guria_welcome_new_profile_trigger after insert on public.profiles for each row execute procedure public.guria_welcome_new_profile();
revoke execute on function public.guria_welcome_new_profile() from public, anon, authenticated;

insert into public.guria_knowledge (title, summary, kind, source, source_url, is_demo)
values ('Como funciona a Banca Digital', 'A Banca organiza leituras, estantes, perfis, seguidores e conversas privadas. Mensagens privadas expiram após 24 horas.', 'site', 'Documentação do produto', null, true)
on conflict do nothing;
