create table if not exists public.shelf_collection_comments (
  id bigint generated by default as identity primary key,
  collection_id text not null references public.shelf_collections(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists shelf_collection_comments_collection_idx
  on public.shelf_collection_comments(collection_id, created_at asc);

alter table public.shelf_collection_comments enable row level security;

drop policy if exists "public collection comments are visible" on public.shelf_collection_comments;
drop policy if exists "users create collection comments" on public.shelf_collection_comments;
drop policy if exists "users delete collection comments" on public.shelf_collection_comments;

create policy "public collection comments are visible"
  on public.shelf_collection_comments for select using (
    exists (
      select 1 from public.shelf_collections collection
      where collection.id = shelf_collection_comments.collection_id
        and collection.owner_id = shelf_collection_comments.owner_id
        and collection.is_public
        and collection.collection_type = 'comic'
    ) and not public.is_blocked_between(user_id)
  );

create policy "users create collection comments"
  on public.shelf_collection_comments for insert with check (
    auth.uid() = user_id
    and public.can_post_content('comment', body)
    and exists (
      select 1 from public.shelf_collections collection
      where collection.id = shelf_collection_comments.collection_id
        and collection.owner_id = shelf_collection_comments.owner_id
        and collection.is_public
        and collection.collection_type = 'comic'
    )
    and not public.is_blocked_between(owner_id)
  );

create policy "users delete collection comments"
  on public.shelf_collection_comments for delete using (
    auth.uid() = user_id or auth.uid() = owner_id or public.is_moderator()
  );

notify pgrst, 'reload schema';
