  function factionPinnedOwnCollectionsMarkupLegacy(faction) {
    const publisher = String(faction.publisher_name || "").trim().toLocaleLowerCase("pt-BR");
    const pinned = [...state.factionPinnedCollections.values()].filter(row => String(row.faction_id) === String(faction.id));
    const catalogs = pinned.map(row => state.factionCatalogs.find(catalog => String(catalog.id) === String(row.catalog_id))).filter(Boolean).map(catalog => ({ ...catalog, item_ids: (Array.isArray(catalog.item_ids) ? catalog.item_ids.map(String) : []).map(id => state.db.library.find(item => String(item.id) === id)).filter(item => item && (!publisher || String(item.publisher || "").trim().toLocaleLowerCase("pt-BR") === publisher)).map(item => item.id) })).filter(catalog => catalog.item_ids.length);
    if (!catalogs.length) return "";
    const body = catalogs.length ? `<div class="publisher-carousel faction-featured-collections">${catalogs.map(catalog => { const ids = Array.isArray(catalog.item_ids) ? catalog.item_ids.map(String) : []; const items = ids.map(id => state.db.library.find(item => String(item.id) === id)).filter(Boolean); const cover = catalog.cover_url || (items[0] ? coverFor(items[0]) : "assets/batmanicon.jpg"); const href = `?pagina=faccoes&faccao=${encodeURIComponent(factionRouteKey(faction.id))}&catalogo=${encodeURIComponent(catalog.id)}`; return `<a class="publisher-card faction-collection-card" href="${escapeHTML(href)}"><div class="publisher-card-cover" style="background-image:url('${escapeHTML(cover)}')"></div><div class="publisher-card-overlay"></div><div class="publisher-card-info"><strong>${escapeHTML(catalog.name)}</strong><span>${items.length} edição(ões)</span></div></a>`; }).join("")}</div>` : '<div class="empty">Nenhuma coleção foi fixada nesta facção.</div>';
    const subtitle = publisher ? `Coleções com edições da editora ${escapeHTML(faction.publisher_name)}.` : "Coleções escolhidas pelos líderes e curadores da facção.";
    return `<section class="section faction-extra-abafac faction-pinned-collections-abafac" data-faction-abafac="pinned-collections" style="--faction-color:${escapeHTML(faction.color)}"><div class="section-head"><div><div class="eyebrow">Curadoria</div><h2 class="section-title">Coleções de quadrinhos em destaque</h2><div class="section-subtitle">${subtitle}</div></div></div>${body}</section>`;
  }

