  function hasLegendaryAccess(profile = state.profile) {
    return ["premium", "moderator", "banca", "admin"].includes(normalizedPlan(profile));
  }
  const PROFILE_BACKGROUND_THEMES = {
    black: { label: "Preto", bg: "#000000", text: "#f5f5f5", muted: "#b5b5bd", surface: "#0d0d10", surface2: "#17171c", surface3: "#25252b", line: "#303038" },
    white: { label: "Branco", bg: "#ffffff", text: "#17171b", muted: "#5f6068", surface: "#f3f3f5", surface2: "#e9e9ed", surface3: "#dcdce1", line: "#c9c9d0" },
    graphite: { label: "Grafite", bg: "#24242a", text: "#f5f5f5", muted: "#b7b7c0", surface: "#303037", surface2: "#3b3b44", surface3: "#494952", line: "#555560" },
    "night-blue": { label: "Azul noite", bg: "#101a2b", text: "#f5f7ff", muted: "#aeb8cc", surface: "#16243a", surface2: "#1e304b", surface3: "#2a4162", line: "#385171" },
    wine: { label: "Vinho", bg: "#2a1118", text: "#fff5f6", muted: "#d1aeb5", surface: "#351720", surface2: "#451d29", surface3: "#5a2937", line: "#713847" },
    forest: { label: "Floresta", bg: "#0d211a", text: "#f1fff7", muted: "#a9c8b7", surface: "#143126", surface2: "#1d4433", surface3: "#285a43", line: "#397457" },
    plum: { label: "Ameixa", bg: "#21132b", text: "#fbf4ff", muted: "#c4aecf", surface: "#2d1b3a", surface2: "#3c2550", surface3: "#513268", line: "#69427e" },
    sand: { label: "Areia", bg: "#332818", text: "#fffaf0", muted: "#d2c09d", surface: "#463820", surface2: "#5a4829", surface3: "#705c35", line: "#8a7246" },
    ocean: { label: "Oceano", bg: "#0c2630", text: "#effcff", muted: "#a8c8cf", surface: "#123640", surface2: "#1b4854", surface3: "#28616e", line: "#377a87" }
  };
  const PROFILE_ACCENT_THEMES = {
    black: { label: "Preto", accent: "#000000", accent2: "#333333" },
    white: { label: "Branco", accent: "#ffffff", accent2: "#d8d8d8" },
    blue: { label: "Azul", accent: "#2f80ed", accent2: "#69a7ff" },
    purple: { label: "Roxo", accent: "#8e44ad", accent2: "#c27be0" },
    green: { label: "Verde", accent: "#27ae60", accent2: "#65d995" },
    orange: { label: "Laranja", accent: "#f2994a", accent2: "#ffc078" },
    pink: { label: "Rosa", accent: "#e84393", accent2: "#ff86c8" },
    cyan: { label: "Ciano", accent: "#00a8cc", accent2: "#62d9f2" },
    teal: { label: "Turquesa", accent: "#00a896", accent2: "#55d8c9" },
    yellow: { label: "Amarelo", accent: "#d9a400", accent2: "#ffe071" },
    indigo: { label: "Índigo", accent: "#5b5bd6", accent2: "#9b9bff" },
    crimson: { label: "Carmesim", accent: "#c2185b", accent2: "#f06292" }
  };
  const SHELF_STYLE_OPTIONS = [
    ["none", "Original", "", false],
    ["sand", "Areia", "assets/prateleiras/Comum/areia.jpg", false],
    ["sponge", "Esponja", "assets/prateleiras/Comum/esponja.jpg", false],
    ["grass", "Grama", "assets/prateleiras/Comum/grama.jpg", false],
    ["classic-wood", "Madeira clássica", "assets/prateleiras/Comum/madeira%20classica.jpg", false],
    ["straw", "Palha", "assets/prateleiras/Comum/palha.jpg", false],
    ["stones", "Pedras", "assets/prateleiras/Comum/pedras.jpg", false],
    ["rustic", "Rústica", "assets/prateleiras/Comum/rustica.jpg", false],
    ["bricks-1", "Tijolos 1", "assets/prateleiras/Comum/tijolos%201.jpg", false],
    ["bricks-2", "Tijolos 2", "assets/prateleiras/Comum/tijolos%202.jpg", false],
    ["log", "Tronco", "assets/prateleiras/Comum/tronco.jpg", false],
    ["crumpled-1", "Amassado 1", "assets/prateleiras/Lenda/amassado%201.png", true],
    ["crumpled-2", "Amassado 2", "assets/prateleiras/Lenda/amassado%202.jpg", true],
    ["box", "Caixa", "assets/prateleiras/Lenda/caixa.png", true],
    ["basket", "Cestinha", "assets/prateleiras/Lenda/cestinha.jpg", true],
    ["comics-a", "Comics A", "assets/prateleiras/Lenda/comics%20A.jpg", true],
    ["comics-b", "Comics B", "assets/prateleiras/Lenda/comics%20B.jpg", true],
    ["comics-l", "Comics L", "assets/prateleiras/Lenda/comics%20L.jpg", true],
    ["comics-m", "Comics M", "assets/prateleiras/Lenda/comics%20M.jpg", true],
    ["comics-v", "Comics V", "assets/prateleiras/Lenda/comics%20V.jpg", true],
    ["style-1", "Estilo 1", "assets/prateleiras/Lenda/estilos%201.jpg", true],
    ["style-2", "Estilo 2", "assets/prateleiras/Lenda/estilos%202.jpg", true],
    ["style-3", "Estilo 3", "assets/prateleiras/Lenda/estilos%203.jpg", true],
    ["style-4", "Estilo 4", "assets/prateleiras/Lenda/estilos%204.jpg", true],
    ["style-5", "Estilo 5", "assets/prateleiras/Lenda/estilos%205.png", true],
    ["jeans", "Jeans", "assets/prateleiras/Lenda/jeans.png", true],
    ["lego-1", "Lego 1", "assets/prateleiras/Lenda/lego%201.jpg", true],
    ["lego-2", "Lego 2", "assets/prateleiras/Lenda/lego%202.jpg", true],
    ["default-1", "Padrão 1", "assets/prateleiras/Lenda/padr%C3%A3o%201.jpg", true],
    ["default-2", "Padrão 2", "assets/prateleiras/Lenda/padr%C3%A3o%202.jpg", true],
    ["default-3", "Padrão 3", "assets/prateleiras/Lenda/padr%C3%A3o%203.jpg", true],
    ["default-5", "Padrão 5", "assets/prateleiras/Lenda/padr%C3%A3o%205.jpg", true],
    ["wood-floor", "Piso de madeira", "assets/prateleiras/Lenda/piso%20de%20madeira.jpg", true],
    ["frame", "Quadro", "assets/prateleiras/Lenda/quadro.jpg", true],
    ["trace", "Traçado", "assets/prateleiras/Lenda/tra%C3%A7ado.jpg", true],
  ];
