  function publicCollectionCard(collection, canManage = false) {
    const blog = collection.collection_type === "blog";
    const factionCatalog = collection.is_faction_catalog === true;
    const count = blog ? (Array.isArray(collection.blog_ids) ? collection.blog_ids.length : 0) : (Array.isArray(collection.item_ids) ? collection.item_ids.length : 0);
    const cover = collection.cover_url || collection.coverUrl || instantCover({ title: collection.name });
    const href = factionCatalog ? `?pagina=faccoes&faccao=${encodeURIComponent(collection.faction_page_key)}&catalogo=${encodeURIComponent(collection.catalog_id)}` : publicProfileHref(collection.username, collection.id);
    const ownerLabel = factionCatalog ? `${collection.faction_emblem || ""} ${collection.faction_name}` : `@${collection.username || "usuário"}`;
    return `<article class="public-shelf-collection-card" data-public-collection="${escapeHTML(collection.id)}" data-public-owner="${escapeHTML(collection.username || "")}" ${factionCatalog ? `data-public-faction-page="${escapeHTML(collection.faction_page_key)}" data-public-faction-catalog="${escapeHTML(collection.catalog_id)}"` : ""} role="link" tabindex="0"><div class="public-shelf-collection-cover has-image" style="background-image:url('${escapeHTML(cover)}')"></div><div class="public-shelf-collection-info"><div class="eyebrow">${collection.is_featured ? "Destaque · " : ""}${factionCatalog ? "Catálogo de facção" : blog ? "Blogs" : "Quadrinhos"}</div><h3>${escapeHTML(collection.name)}</h3><p>${count} item(ns) · ${escapeHTML(ownerLabel)}${collection.likes ? ` · ${collection.likes} curtida(s)` : ""}</p><div class="shelf-section-actions"><span class="shelf-visibility is-public">Pública</span><a class="small-btn" href="${escapeHTML(href)}">Abrir</a>${canManage ? `<button class="small-btn" data-copy-collection="${escapeHTML(collection.id)}" data-copy-username="${escapeHTML(collection.username)}">Compartilhar</button><button class="small-btn" data-collection-feature="${escapeHTML(collection.id)}" data-collection-featured="${collection.is_featured ? "true" : "false"}">${collection.is_featured ? "Remover destaque" : "Destacar"}</button>` : ""}</div></div></article>`;
  }

