  function renderPublicCollectionPage(publicState, category) {
    const profile = publicState.profile;
    const allItems = publicCollectionItems(category, publicState);
    const filter = state.collectionFilter || { field: "all", query: "" };
    const filteredItems = filterCollectionItems(allItems, filter.field, filter.query);
    const sortOrder = publicState.profile?.shelf_sort_orders?.[`category:${category.id}`] || category.sortOrder || "added_desc";
    const items = sortShelfItems(filteredItems, sortOrder, null, publicState.readingProgress);
    const isLiked = publicState.collectionLikes?.has(category.id);
    const likes = publicState.collectionLikeCounts?.get(category.id) || 0;
    const isOwner = String(state.session?.user?.id || "") === String(profile.id || "");
    const storedColor = category.coverStyles?.__themeColor;
    const collectionColor = /^#[0-9a-f]{6}$/i.test(String(storedColor || "")) ? storedColor : "#31202b";
    const cover = category.coverUrl ? `style="background-image:url('${escapeHTML(proxiedImageUrl(category.coverUrl))}')"` : "";
    const colorControl = isOwner ? `<div class="public-collection-color-control"><span>Mudar cor</span><div class="public-collection-color-palette" role="group" aria-label="Cores da coleção">${PUBLIC_COLLECTION_COLOR_OPTIONS.map(([color, label]) => `<button type="button" class="public-collection-color-swatch ${color.toLowerCase() === String(collectionColor).toLowerCase() ? "is-selected" : ""}" style="--swatch-color:${color}" data-public-collection-color="${escapeHTML(category.id)}" data-public-collection-color-value="${color}" aria-label="${label}" title="${label}"></button>`).join("")}</div></div>` : "";
    return `<div class="content public-collection-page"><div class="public-collection-hero" style="--public-collection-color:${escapeHTML(collectionColor)}"><div class="public-collection-icon ${category.coverUrl ? "has-cover" : ""}" ${cover}>${category.coverUrl ? "" : "▣"}</div><div><div class="eyebrow">Coleção pública</div><h1 class="section-title">${escapeHTML(category.name)}</h1><div class="collection-creator-block">${avatarMarkup(profile, "collection-creator-avatar")}<div><a class="collection-creator" href="${escapeHTML(publicProfileHref(profile.username))}">@${escapeHTML(profile.username)}</a>${profile.title ? `<div class="collection-creator-title" style="--title-bg:${safeTitleColor(profile.title_color)}">${escapeHTML(profile.title)}</div>` : ""}</div></div><div class="section-subtitle">${allItems.length} item(ns)</div>${colorControl}</div></div><div class="section-head"><div><h2 class="section-title">${escapeHTML(category.name)}</h2><div class="section-subtitle">Uma coleção compartilhada da Banca Digital</div></div><div class="shelf-section-actions"><button class="small-btn ${isLiked ? "is-liked" : ""}" data-like-collection="${escapeHTML(category.id)}" data-like-owner="${escapeHTML(profile.id)}">${isLiked ? "♥ Curtida" : "♡ Curtir"} · ${likes}</button><button class="small-btn" data-copy-collection="${escapeHTML(category.id)}" data-copy-username="${escapeHTML(profile.username)}">Copiar link</button><a class="small-btn" href="${escapeHTML(publicProfileHref(profile.username))}">Ver perfil</a></div></div><form class="collection-filter" data-collection-filter-form><select name="field"><option value="all" ${filter.field === "all" ? "selected" : ""}>Filtrar por qualquer campo</option><option value="author" ${filter.field === "author" ? "selected" : ""}>Autor</option><option value="publisher" ${filter.field === "publisher" ? "selected" : ""}>Editora</option><option value="character" ${filter.field === "character" ? "selected" : ""}>Personagem</option><option value="tag" ${filter.field === "tag" ? "selected" : ""}>Gênero / tag</option><option value="seriesTitle" ${filter.field === "seriesTitle" ? "selected" : ""}>Série</option><option value="title" ${filter.field === "title" ? "selected" : ""}>Título</option></select><input name="query" value="${escapeHTML(filter.query)}" placeholder="Digite para filtrar a coleção"><button class="small-btn">Filtrar</button></form><div class="collection-results-meta">${items.length} de ${allItems.length} item(ns)</div><div class="results-grid">${items.map(item => card(item, publicState.readingProgress, publicState.favoriteIds)).join("") || '<div class="empty">Nenhum quadrinho corresponde ao filtro.</div>'}</div></div>`;
  }

